autozip --force added

diff --git a/bin/autounzip b/bin/autounzip
--- a/bin/autounzip
+++ b/bin/autounzip
@@ -1,8 +1,9 @@
 #!/bin/bash
-# AUTOUNZIP V2P6
+# AUTOUNZIP V2P7
 # ============ Functions ============
 DN=$(dirname ${0})
 exec 1>&2
+ISFORCE=false
 . $DN/../lib/libautozip && echo -e "\e[33mlibautozip loaded.\e[0m" || {
     echo -e "\e[31mFail to load libautozip.\e[0m"
     exit 1
@@ -87,14 +88,27 @@ ext=${fulln##*.}
 if [ ${fn##*.} = "tar" ]; then
     ext="tar.${ext}"
     fn=${fn%.*}
-    elif [[ ${fulln} = *".part1.rar" ]];then
-        fn=$(echo ${fulln}|sed "s/.part1.rar//")
+elif [[ ${fulln} == *".part1.rar" ]]; then
+    fn=$(echo ${fulln} | sed "s/.part1.rar//")
 fi
+case ${ext} in
+"tar" | "tar.gz" | "tgz" | "tar.GZ" | "tar.xz" | "txz" | "tar.bz2" | "tbz" | "tar.lzma" | "tar.lz" | "tlz" | "gz" | "GZ" | "xz" | "bz2" | "lz" | "lzma" | "7z" | "zip" | "rar")
+    echo -e "\e[33mReceived: ${0} ${fulln} ${OPT} ==>Extension=${ext}\e[0m"
+    ;;
+*)
+    echo -e "\e[31mERROR: Extension ${ext} invalid!\e[0m"
+    exit 1
+    ;;
+esac
 if [ -e ${fn} ]; then
-    echo -e "\e[31mWARNING: ${fn} exists! Will rename ${fn} as ${fn}.bak.\e[0m"
-    DO mv -f ${fn} ${fn}.bak
+    if ${ISFORCE}; then
+        echo -e "\e[31mWARNING: ${fn} exists! Will remove ${fn}.\e[0m"
+        DO rm -rf ${fn}
+    else
+        echo -e "\e[31mWARNING: ${fn} exists! Will rename ${fn} as ${fn}.bak.\e[0m"
+        DO mv -f ${fn} ${fn}.bak
+    fi
 fi
-echo -e "\e[33mReceived: ${0} ${fulln} ${OPT} ==>Extension=${ext}\e[0m"
 # ============ Makt tmp ============
 mktmp
 # ============ Start Compressing ============
diff --git a/lib/libautozip b/lib/libautozip
--- a/lib/libautozip
+++ b/lib/libautozip
@@ -1,5 +1,5 @@
 #!/bin/bash
-# LIBAUTOZIP V2P6
+# LIBAUTOZIP V2P7
 USESPLIT=false
 REMOVE=false
 #Load libopt
@@ -75,7 +75,7 @@ function preck() {
             i=$((${i} + 1))
         done <${CONFN}
         unset line
-        if [ ${conf[0]} = "PARALLEL" ] && [ $(PARALLEL) -eq 0 ] ; then
+        if [ ${conf[0]} = "PARALLEL" ] && [ $(PARALLEL) -eq 0 ]; then
             USEPARALLEL=true
             PP="/usr/bin/parallel"
             echo -e "\e[33mWill use GNU Parallel if possible.\e[0m"
@@ -184,8 +184,11 @@ function ppopt() {
                 exit 0
                 ;;
             "-v" | "--version")
-                echo "Version 2 patch 6"
+                echo "Version 2 patch 7"
                 exit 0
+                ;;
+            "--force")
+                ISFORCE=true
                 ;;
             --force-parallel\:*)
                 PP=${opt:17}
@@ -209,9 +212,9 @@ function ppopt() {
                 ;;
 
             "-s" | "--split")
-            if ! ${ISAOTOZIP};then
-              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
-                exit 1
+                if ! ${ISAOTOZIP}; then
+                    echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                    exit 1
                 fi
                 USESPLIT=true
                 case ${ext} in
@@ -224,17 +227,17 @@ function ppopt() {
                 esac
                 ;;
             -s\:*)
-                          if ! ${ISAOTOZIP};then
-              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
-                exit 1
+                if ! ${ISAOTOZIP}; then
+                    echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                    exit 1
                 fi
                 USESPLIT=true
                 SPLIT=${opt:3}
                 ;;
             --split\:*)
-                          if ! ${ISAOTOZIP};then
-              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
-                exit 1
+                if ! ${ISAOTOZIP}; then
+                    echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                    exit 1
                 fi
                 USESPLIT=true
                 SPLIT=${opt:8}
