small bugs fixed.

diff --git a/bin/autounzip b/bin/autounzip
--- a/bin/autounzip
+++ b/bin/autounzip
@@ -1,9 +1,12 @@
 #!/bin/bash
-# AUTOUNZIP V2P4
+# AUTOUNZIP V2P5
 # ============ Functions ============
 DN=$(dirname ${0})
 exec 1>&2
-. $DN/../lib/libautozip && echo -e "\e[33mlibautozip loaded.\e[0m" || { echo -e "\e[31mFail to load libautozip.\e[0m";exit 1; }
+. $DN/../lib/libautozip && echo -e "\e[33mlibautozip loaded.\e[0m" || {
+    echo -e "\e[31mFail to load libautozip.\e[0m"
+    exit 1
+}
 LIBDO_TOP_PID=${$}
 # Make a number 3 digit
 function fixthree() {
@@ -84,6 +87,8 @@ ext=${fulln##*.}
 if [ ${fn##*.} = "tar" ]; then
     ext="tar.${ext}"
     fn=${fn%.*}
+    elif [[ ${fulln} = *".part1.rar" ]];then
+        fn=$(echo ${fulln}|sed "s/.part1.rar//")
 fi
 if [ -e ${fn} ]; then
     echo -e "\e[31mWARNING: ${fn} exists! Will rename ${fn} as ${fn}.bak.\e[0m"
@@ -118,7 +123,7 @@ case ${ext} in
         echo -e "\e[31mERROR: GZip NO exist!\e[0m"
         exit 1
     fi
-        if ! [ $(TAR) -eq 0 ]; then
+    if ! [ $(TAR) -eq 0 ]; then
         echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
         exit 1
     fi
@@ -228,7 +233,7 @@ case ${ext} in
         exit 1
     fi
     if [ -f ${fn}.z01 ]; then
-        if ! [ $ZIP -eq 0 ]; then
+        if ! [ $(ZIP) -eq 0 ]; then
             echo -e "\e[31mERROR: zip NO exist!\e[0m"
             exit 1
         fi
diff --git a/bin/autozip b/bin/autozip
--- a/bin/autozip
+++ b/bin/autozip
@@ -1,5 +1,5 @@
 #!/bin/bash
-# AUTOZIP V2P4
+# AUTOZIP V2P5
 # ============ Functions ============
 DN=$(dirname ${0})
 exec 1>&2
@@ -124,18 +124,19 @@ function ckLVL() {
 # Backup if exist.
 function bupf() {
     if ${USESPLIT}; then
-        if [ -e ${fn}.${ext}.[0-9][0-9][0-9] ]; then
+        if [ -e ${fn}.${ext}.001 ]; then
             for tfn in ${fn}.${ext}.[0-9][0-9][0-9]; do
                 DO mv -f ${tfn} ${tfn}.bak
             done
-        elif [ -e ${fn}.part*.${ext} ]; then
-            for tfn in ${fn}.part*.${ext}; do
+        elif [ -e ${fn}.part1.rar ]; then
+            for tfn in ${fn}.part*.rar; do
                 DO mv -f ${tfn} ${tfn}.bak
             done
-        elif [ -e ${fn}.z[0-9][0-9] ]; then
+        elif [ -e ${fn}.z01 ]; then
             for tfn in ${fn}.z[0-9][0-9]; do
                 DO mv -f ${tfn} ${tfn}.bak
             done
+            DO mv -f ${fn}.zip ${fn}.zip.bak
         elif [ -e ${fn}.${ext} ]; then
             DO mv -f ${fn}.${ext} ${fn}.${ext}.bak
         fi
@@ -175,7 +176,7 @@ bupf
 # ============ Makt tmpdir ============
 mktmp
 # ============ Start Compressing ============
-if ${USEPARALLEL}; then PAR="$PP --pipe --recend '' -k"; fi
+if ${USEPARALLEL}; then PAR="${PP} --pipe --recend '' -k"; fi
 case ${ext} in
 "tar") # ============ tar ============
     if ${USESPLIT}; then
@@ -189,14 +190,18 @@ case ${ext} in
         echo -e "\e[31mERROR: GZip NO exist!\e[0m"
         exit 1
     fi
-    if [ $(PIGZ) -eq 0 ]; then cmd="pigz"; else cmd="${PAR} gzip"; fi
+    if [ $(PIGZ) -eq 0 ] && ${USEPARALLEL}; then
+        cmd="pigz"
+    else
+        cmd="${PAR} gzip"
+    fi
     if ${USESPLIT}; then
         DO tar cv ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
         for tfn in ${tempdir}/${fn}.*; do
-            DO cat ${tfn}\|$cmd ${LVL} \>${fn}.${ext}.${tfn:0-3}
+            DO cat ${tfn}\|${cmd} ${LVL} \>${fn}.${ext}.${tfn:0-3}
         done
     else
-        DO tar cv ${fn}\|$cmd ${LVL} \>${fn}.${ext}
+        DO tar cv ${fn}\|${cmd} ${LVL} \>${fn}.${ext}
     fi
     ;;
 "tar.xz" | "txz") # ============ txz ============
@@ -204,7 +209,11 @@ case ${ext} in
         echo -e "\e[31mERROR: XZ NO exist!\e[0m"
         exit 1
     fi
-    if ${USEPARALLEL}; then PAR="-T0"; fi
+    if ${USEPARALLEL}; then
+        PAR="--threads=0"
+    else
+        echo "dsafsefs"
+    fi
     if ${USESPLIT}; then
         DO tar cv ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
         for tfn in ${tempdir}/${fn}.*; do
@@ -236,10 +245,10 @@ case ${ext} in
     if ${USESPLIT}; then
         DO tar cv ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
         for tfn in ${tempdir}/${fn}.*; do
-            DO cat ${tfn}\|xz --format=lzma ${LVL}\>${fn}.${ext}.${tfn:0-3}
+            DO cat ${tfn}\|${PAR} xz --format=lzma ${LVL}\>${fn}.${ext}.${tfn:0-3}
         done
     else
-        DO tar cv ${fn}\|xz --format=lzma ${LVL} \>${fn}.${ext}
+        DO tar cv ${fn}\|${PAR} xz --format=lzma ${LVL} \>${fn}.${ext}
     fi
     ;;
 "gz" | "GZ") # ============ gz ============
@@ -262,10 +271,8 @@ case ${ext} in
     fi
     ${ext}="gz"
     if ${USESPLIT}; then
-        DO tar cv ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
-        for tfn in ${tempdir}/${fn}.*; do
-            DO cat ${tfn}\|${PAR} bgzip ${LVL}\>${fn}.${ext}.${tfn:0-3}
-        done
+        echo -e "\e[31mERROR: BGZip do not support split!\e[0m"
+        exit 1
     else
         DO cat ${fn}\|${PAR} bgzip ${LVL}\>${fn}.${ext}
     fi
@@ -275,7 +282,7 @@ case ${ext} in
         echo -e "\e[31mERROR: XZ NO exist!\e[0m"
         exit 1
     fi
-    if ${USEPARALLEL}; then PAR="-T0"; fi
+    if ${USEPARALLEL}; then PAR="--threads=0"; fi
     if ${USESPLIT}; then
         DO cat ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
         for tfn in ${tempdir}/${fn}.*; do
@@ -307,10 +314,10 @@ case ${ext} in
     if ${USESPLIT}; then
         DO cat ${fn}\|split -a 3 --numeric-suffixes=001 -b ${SPLIT} - ${tempdir}/${fn}.
         for tfn in ${tempdir}/${fn}.*; do
-            DO cat ${tfn}\|xz --format=lzma ${LVL}\>${fn}.${ext}.${tfn:0-3}
+            DO cat ${tfn}\|${PAR} xz --format=lzma ${LVL}\>${fn}.${ext}.${tfn:0-3}
         done
     else
-        DO cat ${fn}\|xz --format=lzma ${LVL}\>${fn}.${ext}
+        DO cat ${fn}\|${PAR} xz --format=lzma ${LVL}\>${fn}.${ext}
     fi
     ;;
 "7z") # ============ 7z ============
diff --git a/bin/azman b/bin/azman
--- a/bin/azman
+++ b/bin/azman
@@ -1,5 +1,5 @@
 #!/bin/bash
-# AZMAN V1
+# AZMAN V1P1
 DN=$(dirname ${0})
 exec 1>&2
 ISAUTOZIP=True
@@ -40,114 +40,114 @@ echo -e "\e[33mReceived: ${0} ${azcmd} ${fulln} ${OPT} ==>Extension=${ext}\e[0m"
 # ============ Start ============
 case ${azcmd} in
 "list")
-case ${ext} in
-"tar") # ============ tar ============
-    if ! [ $(TAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
-        exit 1
-    fi
-        tar tvf ${fulln}
-    ;;
-"tar.gz" | "tgz" | "tar.GZ") # ============ tgz ============
-    if ! [ $(GZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: GZip NO exist!\e[0m"
-        exit 1
-    fi
+    case ${ext} in
+    "tar") # ============ tar ============
         if ! [ $(TAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
-        exit 1
-    fi
-tar tzvf ${fulln}
+            echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
+            exit 1
+        fi
+        tar tvf ${fulln}
+        ;;
+    "tar.gz" | "tgz" | "tar.GZ") # ============ tgz ============
+        if ! [ $(GZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: GZip NO exist!\e[0m"
+            exit 1
+        fi
+        if ! [ $(TAR) -eq 0 ]; then
+            echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
+            exit 1
+        fi
+        tar tzvf ${fulln}
+        ;;
+    "tar.xz" | "txz") # ============ txz ============
+        if ! [ $(XZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: XZ NO exist!\e[0m"
+            exit 1
+        fi
+        if ! [ $(TAR) -eq 0 ]; then
+            echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
+            exit 1
+        fi
+        tar tJvf ${fulln}
+        ;;
+    "tar.bz2" | "tbz") # ============ tbz ============
+        if ! [ $(BZIP2) -eq 0 ]; then
+            echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
+            exit 1
+        fi
+        if ! [ $(TAR) -eq 0 ]; then
+            echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
+            exit 1
+        fi
+        tar tjvf ${fulln}
+        ;;
+    "tar.lzma" | "tar.lz" | "tlz") # ============ tlz ============
+        if ! [ $(XZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: LZMA SDK NO exist!\e[0m"
+            exit 1
+        fi
+        if ! [ $(TAR) -eq 0 ]; then
+            echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
+            exit 1
+        fi
+        tar tvf --lzma ${fulln}
+        ;;
+    "gz" | "GZ") # ============ gz ============
+        if ! [ $(GZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: GZip NO exist!\e[0m"
+            exit 1
+        fi
+        gzip -l ${fulln}
+        ;;
+    "xz") # ============ xz ============
+        if ! [ $(XZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: XZ NO exist!\e[0m"
+            exit 1
+        fi
+        xz -l ${fulln}
+        ;;
+    "bz2") # ============ bz2 ============
+        if ! [ $(BZIP2) -eq 0 ]; then
+            echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
+            exit 1
+        fi
+        echo -e "\e[31mERROR: BZip2 do not support this function!\e[0m"
+        ;;
+    "lz" | "lzma") # ============ lz ============
+        if ! [ $(XZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: XZ NO exist!\e[0m"
+            exit 1
+        fi
+        echo -e "\e[31mERROR: XZ Utils do not support this function!\e[0m"
+        ;;
+    "7z") # ============ 7z ============
+        if ! [ $(Z7) -eq 0 ]; then
+            echo -e "\e[31mERROR: p7zip NO exist!\e[0m"
+            exit 1
+        fi
+        7za l ${fulln}
+        ;;
+    "zip") # ============ zip ============
+        if ! [ $(UNZIP) -eq 0 ]; then
+            echo -e "\e[31mERROR: unzip NO exist!\e[0m"
+            exit 1
+        fi
+        unzip -v ${fulln}
+        ;;
+    "rar")
+        if ! [ $(RAR) -eq 0 ]; then
+            echo -e "\e[31mERROR: rar NO exist!\e[0m"
+            exit 1
+        fi
+        rar v ${fulln}
+        ;;
+    esac
+    # ============ Finished ============
+    echo -e "\e[33mFinished.\e[0m"
+    exit 0
     ;;
-"tar.xz" | "txz") # ============ txz ============
-    if ! [ $(XZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: XZ NO exist!\e[0m"
-        exit 1
-    fi
-    if ! [ $(TAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
-        exit 1
-    fi
-tar tJvf ${fulln}
-    ;;
-"tar.bz2" | "tbz") # ============ tbz ============
-    if ! [ $(BZIP2) -eq 0 ]; then
-        echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
-        exit 1
-    fi
-    if ! [ $(TAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
-        exit 1
-    fi
-tar tjvf ${fulln}
-    ;;
-"tar.lzma" | "tar.lz" | "tlz") # ============ tlz ============
-    if ! [ $(XZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: LZMA SDK NO exist!\e[0m"
-        exit 1
-    fi
-    if ! [ $(TAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
-        exit 1
-    fi
-tar tvf --lzma ${fulln}
-    ;;
-"gz" | "GZ") # ============ gz ============
-    if ! [ $(GZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: GZip NO exist!\e[0m"
-        exit 1
-    fi
-    gzip -l ${fulln}
-    ;;
-"xz") # ============ xz ============
-    if ! [ $(XZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: XZ NO exist!\e[0m"
-        exit 1
-    fi
- xz -l ${fulln}
-    ;;
-"bz2") # ============ bz2 ============
-    if ! [ $(BZIP2) -eq 0 ]; then
-        echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
-        exit 1
-    fi
-    echo -e "\e[31mERROR: BZip2 do not support this function!\e[0m"
-    ;;
-"lz" | "lzma") # ============ lz ============
-    if ! [ $(XZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: XZ NO exist!\e[0m"
-        exit 1
-    fi
-    echo -e "\e[31mERROR: XZ Utils do not support this function!\e[0m"
-    ;;
-"7z") # ============ 7z ============
-    if ! [ $(Z7) -eq 0 ]; then
-        echo -e "\e[31mERROR: p7zip NO exist!\e[0m"
-        exit 1
-    fi
-    7za l ${fulln}
-    ;;
-"zip") # ============ zip ============
-    if ! [ $(UNZIP) -eq 0 ]; then
-        echo -e "\e[31mERROR: unzip NO exist!\e[0m"
-        exit 1
-    fi
-    unzip -v ${fulln}
-    ;;
-"rar")
-    if ! [ $(RAR) -eq 0 ]; then
-        echo -e "\e[31mERROR: rar NO exist!\e[0m"
-        exit 1
-    fi
-    rar v ${fulln}
-    ;;
-esac
-# ============ Finished ============
-echo -e "\e[33mFinished.\e[0m"
-exit 0
-;;
 *)
-  echo -e "\e[31mERROR: subcommand '${azcmd}' not exist!\e[0m"
-        exit 1
-  ;;
+    echo -e "\e[31mERROR: subcommand '${azcmd}' not exist!\e[0m"
+    exit 1
+    ;;
 esac
