Small bugs fixed

diff --git a/bin/autozip b/bin/autozip
--- a/bin/autozip
+++ b/bin/autozip
@@ -84,11 +84,12 @@ if [ -n "${SPLIT:-}" ]; then
         exit 1
     fi
 fi
+if ! "${mysplit}" --help&>>/dev/null;then
+    echo  -e "\e[31mERROR: '${mysplit}' is BSD split, which is not supported.\e[0m"
+    exit 1
+fi
 unset VALIDSPLIT
 case "${ext}" in
-"tar")
-    lvl_able=""
-    ;;
 "xz" | "tar.xz" | "txz" | "zip" | "lzma" | "tlz" | "tar.lzma")
     lvl_able="[0123456789]"
     ;;
@@ -148,7 +149,7 @@ else
         fi
         unset tfn
     else
-        if [ -e ${fn}.${ext} ]; then
+        if [ -e "${fn}".${ext} ]; then
             "${mymv}" -f "${fn}".${ext} "${fn}".${ext}.bak
         fi
     fi
@@ -163,7 +164,7 @@ SPL=''
 case ${ext} in
 "tar") # ============ tar ============
     if [ -n "${SPLIT:-}" ]; then
-        "${mytar}" -f - -cv "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${fn}".${ext}.
+        "${mytar}" -f - -cv "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${fn}".${ext}.
     else
         "${mytar}" -cvf "${fn}".${ext} "${fn}"
     fi
@@ -180,7 +181,7 @@ case ${ext} in
     fi
     
     if [ -n "${SPLIT:-}" ]; then
-        "${mytar}" -f - -cv "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        "${mytar}" -f - -cv "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             "${mycat}" "${tfn}" | ${cmd} ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -198,7 +199,7 @@ case ${ext} in
         PAR="--threads=0"
     fi
     if [ -n "${SPLIT:-}" ]; then
-        "${mytar}" -f - -cv "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        "${mytar}" -f - -cv "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | "${myxzip}" ${PAR} ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -212,7 +213,7 @@ case ${ext} in
         exit 1
     fi
     if [ -n "${SPLIT:-}" ]; then
-        "${mytar}" -f - -cv "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        "${mytar}" -f - -cv "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | ${PAR} "${mybzip2}" ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -226,7 +227,7 @@ case ${ext} in
         exit 1
     fi
     if [ -n "${SPLIT:-}" ]; then
-        "${mytar}" -f - -cv "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        "${mytar}" -f - -cv "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | ${PAR} "${myxzip}" --format=lzma ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -245,7 +246,7 @@ case ${ext} in
         cmd="${PAR} ${mygzip}"
     fi
     if [ -n "${SPLIT:-}" ]; then
-        cat "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        cat "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | ${cmd} ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -273,7 +274,7 @@ case ${ext} in
     fi
     if ${USEPARALLEL}; then PAR="--threads=0"; fi
     if [ -n "${SPLIT:-}" ]; then
-        cat "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        cat "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in ${tempdir}/${fn}.*; do
             cat "${tfn}" | "${myxzip}" ${PAR} ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -287,7 +288,7 @@ case ${ext} in
         exit 1
     fi
     if [ -n "${SPLIT:-}" ]; then
-        cat "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        cat "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | ${PAR} "${mybzip2}" ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
@@ -301,7 +302,7 @@ case ${ext} in
         exit 1
     fi
     if [ -n "${SPLIT:-}" ]; then
-        cat "${fn}" | split -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
+        cat "${fn}" |"${mysplit}" -a 3 --numeric-suffixes=001 -b ${SPLIT} - "${tempdir}"/"${fn}".
         for tfn in "${tempdir}"/"${fn}".*; do
             cat "${tfn}" | ${PAR} "${myxzip}" --format=lzma ${LVL} >"${fn}".${ext}.${tfn:0-3}
         done
