Phase 1

diff --git a/bin/autounzip b/bin/autounzip
--- a/bin/autounzip
+++ b/bin/autounzip
@@ -1,60 +1,61 @@
 #!/bin/bash
+# AUTOUNZIP V2P2
 # ============ Functions ============
-DN=$(dirname $0)
+DN=$(dirname ${0})
 exec 1>&2
-. $DN/libautozip && echo -e "\e[33mlibautozip loaded.\e[0m"
-LIBDO_TOP_PID=$$
+. $DN/../lib/libautozip && echo -e "\e[33mlibautozip loaded.\e[0m" || { echo -e "\e[31mFail to load libautozip.\e[0m";exit 1; }
+LIBDO_TOP_PID=${$}
 # Make a number 3 digit
 function fixthree() {
-    local fout=""$1
+    local fout=${1}
     while [ ${#fout} -lt 3 ]; do
-        fout="0"$fout
+        fout="0"${fout}
     done
-    echo $fout
+    echo ${fout}
 }
 # Standard_C heads
 function stdc_h() {
     local file_i=1
     local in_i=001
-    if $USEPARALLEL; then
-        while [ -f $fulln.$in_i ]; do
-            echo -e "\e[33mWill execute: echo \"cat ${PWD}/$fulln.$in_i|$@>>$tempdir/$in_i\">>$tempdir/$in_i.sh\e[0m"
-            echo "cat ${PWD}/$fulln.$in_i|$@>>$tempdir/$in_i" >>$tempdir/$in_i.sh
-            chmod +x $tempdir/$in_i.sh
-            file_i=$(($file_i + 1))
-            in_i=$(fixthree $file_i)
+    if ${USEPARALLEL}; then
+        while [ -f ${fulln}.${in_i} ]; do
+            echo -e "\e[33mWill execute: echo \"cat ${PWD}/${fulln}.${in_i}|$@>>${tempdir}/${in_i}\">>${tempdir}/${in_i}.sh\e[0m"
+            echo "cat ${PWD}/${fulln}.${in_i}|$@>>${tempdir}/${in_i}" >>${tempdir}/${in_i}.sh
+            chmod +x ${tempdir}/${in_i}.sh
+            file_i=$((${file_i} + 1))
+            in_i=$(fixthree ${file_i})
         done
-        DO find $tempdir/*.sh\|$PP bash
+        DO find ${tempdir}/*.sh\|$PP bash
     else
-        while [ -f $fulln.$in_i ]; do
-            DO cat $fulln.$in_i\|$@\>\>$tempdir/$in_i
-            file_i=$(($file_i + 1))
-            in_i=$(fixthree $file_i)
+        while [ -f ${fulln}.${in_i} ]; do
+            DO cat ${fulln}.${in_i}\|$@\>\>${tempdir}/${in_i}
+            file_i=$((${file_i} + 1))
+            in_i=$(fixthree ${file_i})
         done
     fi
 }
 # standard TAR creator
 function stdtc() {
-    stdc_h $@
+    stdc_h ${@}
     local file_i=1
     local in_i=001
-    while [ -f $fulln.$in_i ]; do
-        DO cat $tempdir/$in_i\>\>$tempf
-        file_i=$(($file_i + 1))
-        in_i=$(fixthree $file_i)
+    while [ -f ${fulln}.${in_i} ]; do
+        DO cat ${tempdir}/${in_i}\>\>${tempf}
+        file_i=$((${file_i} + 1))
+        in_i=$(fixthree ${file_i})
     done
     unset file_i in_1
-    DO tar xvf $tempf
+    DO tar xvf ${tempf}
 }
 # standard FILE creator
 function stdfc() {
-    stdc_h $@
+    stdc_h ${@}
     local file_i=1
     local in_i=001
-    while [ -f $fulln.$in_i ]; do
-        DO cat $tempdir/$in_i\>\>$fn
-        file_i=$(($file_i + 1))
-        in_i=$(fixthree $file_i)
+    while [ -f ${fulln}.${in_i} ]; do
+        DO cat ${tempdir}/${in_i}\>\>${fn}
+        file_i=$((${file_i} + 1))
+        in_i=$(fixthree ${file_i})
     done
     unset file_i in_1
 }
@@ -66,50 +67,50 @@ preck
 ISAOTOZIP=false
 ppopt $@
 # ============ Possess arguments ============
-STDI=($STDS)
+STDI=(${STDS})
 fulln=${STDI[0]}
-if [ -z $fulln ]; then
+if [ -z ${fulln} ]; then
     autozipck
     exit 0
-elif [ -e "$fulln.001" ]; then
+elif [ -e "${fulln}.001" ]; then
     USESPLIT=true
-elif ! [ -e $fulln ]; then
-    echo -e "\e[31mERROR: Filename '$fulln' invalid.\e[0m"
+elif ! [ -e ${fulln} ]; then
+    echo -e "\e[31mERROR: Filename '${fulln}' invalid.\e[0m"
     exit 1
 fi
-fulln=$(mfn $fulln)
+fulln=$(mfn ${fulln})
 fn=${fulln%.*}
 ext=${fulln##*.}
 if [ ${fn##*.} = "tar" ]; then
-    ext="tar.$ext"
+    ext="tar.${ext}"
     fn=${fn%.*}
 fi
-if [ -e $fn ]; then
-    echo -e "\e[31mWARNING: $fn exists! Will rename $fn as $fn.bak.\e[0m"
-    mv -f $fn $fn.bak
+if [ -e ${fn} ]; then
+    echo -e "\e[31mWARNING: ${fn} exists! Will rename ${fn} as ${fn}.bak.\e[0m"
+    mv -f ${fn} ${fn}.bak
 fi
-echo -e "\e[33mReceived: $0 $fulln $OPT ==>Extension=$ext\e[0m"
+echo -e "\e[33mReceived: $0 ${fulln} $OPT ==>Extension=${ext}\e[0m"
 # ============ Makt tmp ============
 mktmp
 # ============ Start Compressing ============
-case $ext in
+case ${ext} in
 "tar") # ============ tar ============
     if ! [ $(TAR) -eq 0 ]; then
         echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         file_i=1
         in_i=001
-        while [ -f $fulln.$in_i ]; do
-            DO cat $fulln.$in_i >>$tempf
-            file_i=$(($file_i + 1))
-            in_i=$(fixthree $file_i)
+        while [ -f ${fulln}.${in_i} ]; do
+            DO cat ${fulln}.${in_i} >>${tempf}
+            file_i=$((${file_i} + 1))
+            in_i=$(fixthree ${file_i})
         done
         unset file_i in_1
-        DO tar xvf $tempf
+        DO tar xvf ${tempf}
     else
-        DO tar xvf $fulln
+        DO tar xvf ${fulln}
     fi
     ;;
 "tar.gz" | "tgz" | "tar.GZ") # ============ tgz ============
@@ -117,13 +118,13 @@ case $ext in
         echo -e "\e[31mERROR: GZip NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdtc "gzip -dk"
     else
-        if $USEPARALLEL && [ $PIGZ -eq 0 ]; then
-            DO pigz -d $fulln\|tar xv \>$fn
+        if ${USEPARALLEL} && [ $(PIGZ) -eq 0 ]; then
+            DO pigz -d ${fulln}\|tar xv \>${fn}
         else
-            DO tar xzvf $fulln
+            DO tar xzvf ${fulln}
         fi
     fi
     ;;
@@ -132,10 +133,10 @@ case $ext in
         echo -e "\e[31mERROR: XZ NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdtc "xz -dk"
     else
-        DO tar xJvf $fulln
+        DO tar xJvf ${fulln}
     fi
     ;;
 "tar.bz2" | "tbz") # ============ tbz ============
@@ -143,10 +144,10 @@ case $ext in
         echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdtc "bzip2 -dk"
     else
-        DO tar xjvf $fulln
+        DO tar xjvf ${fulln}
     fi
     ;;
 "tar.lzma" | "tar.lz" | "tlz") # ============ tlz ============
@@ -154,10 +155,10 @@ case $ext in
         echo -e "\e[31mERROR: LZMA SDK NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdtc "xz -dk --format=lzma"
     else
-        DO tar xvf --lzma $fulln
+        DO tar xvf --lzma ${fulln}
     fi
     ;;
 "gz" | "GZ") # ============ gz ============
@@ -165,13 +166,13 @@ case $ext in
         echo -e "\e[31mERROR: GZip NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdfc "gzip -dk"
     else
-        if $USEPARALLEL && [ $PIGZ -eq 0 ]; then
-            DO cat $fulln\|pigz -d\>$fn
+        if ${USEPARALLEL} && [ $PIGZ -eq 0 ]; then
+            DO cat ${fulln}\|pigz -d\>${fn}
         else
-            DO cat $fulln\|gzip -d\>$fn
+            DO cat ${fulln}\|gzip -d\>${fn}
         fi
     fi
     ;;
@@ -180,10 +181,10 @@ case $ext in
         echo -e "\e[31mERROR: XZ NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdfc "xz -dk"
     else
-        DO xz -dk $fulln
+        DO xz -dk ${fulln}
     fi
     ;;
 "bz2") # ============ bz2 ============
@@ -191,10 +192,10 @@ case $ext in
         echo -e "\e[31mERROR: BZip2 NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdfc "bzip2 -dk"
     else
-        DO bzip2 -dk $fulln
+        DO bzip2 -dk ${fulln}
     fi
     ;;
 "lz" | "lzma") # ============ lz ============
@@ -202,10 +203,10 @@ case $ext in
         echo -e "\e[31mERROR: XZ NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         stdfc "xz -dk --format=lzma"
     else
-        DO xz -dk --format=lzma $fulln
+        DO xz -dk --format=lzma ${fulln}
     fi
     ;;
 "7z") # ============ 7z ============
@@ -213,25 +214,25 @@ case $ext in
         echo -e "\e[31mERROR: p7zip NO exist!\e[0m"
         exit 1
     fi
-    if $USESPLIT; then SUFF=".001"; fi
-    if $USEPARALLEL; then PAR="-mmt0"; fi
-    DO 7za $PAR x $fulln$SUFF
+    if ${USESPLIT}; then SUFF=".001"; fi
+    if ${USEPARALLEL}; then PAR="-mmt0"; fi
+    DO 7za ${PAR} x ${fulln}${SUFF}
     ;;
 "zip") # ============ zip ============
     if ! [ $(UNZIP) -eq 0 ]; then
         echo -e "\e[31mERROR: unzip NO exist!\e[0m"
         exit 1
     fi
-    if [ -f $fn.z01 ]; then
+    if [ -f ${fn}.z01 ]; then
         if ! [ $ZIP -eq 0 ]; then
             echo -e "\e[31mERROR: zip NO exist!\e[0m"
             exit 1
         fi
-        DO cp $fn.z* $tempdir/
-        DO zip -FF $tempdir/$fn.zip --out $tempdir/$fn.fzip
-        DO unzip $tempdir/$fn.fzip
+        DO cp ${fn}.z* ${tempdir}/
+        DO zip -FF ${tempdir}/${fn}.zip --out ${tempdir}/${fn}.fzip
+        DO unzip ${tempdir}/${fn}.fzip
     else
-        DO unzip $fulln
+        DO unzip ${fulln}
     fi
     ;;
 "rar")
@@ -239,24 +240,24 @@ case $ext in
         echo -e "\e[31mERROR: unrar NO exist!\e[0m"
         exit 1
     fi
-    if $USEPARALLEL; then PAR="-mt8"; fi
-    DO unrar $PAR x $fulln
+    if ${USEPARALLEL}; then PAR="-mt8"; fi
+    DO unrar ${PAR} x ${fulln}
     ;;
 esac
 # ============ Finished ============
 echo -e "\e[33mRemoving temporary resources...\e[0m"
-rm -rf $tempdir $tempf
+rm -rf ${tempdir} ${tempf}
 if $REMOVE; then
-    if $USESPLIT; then
+    if ${USESPLIT}; then
         file_i=1
         in_i=001
-        while [ -f $fulln.$in_i ]; do
-            DO rm -rf $fulln.$in_i
-            file_i=$(($file_i + 1))
-            in_i=$(fixthree $file_i)
+        while [ -f ${fulln}.${in_i} ]; do
+            DO rm -rf ${fulln}.${in_i}
+            file_i=$((${file_i} + 1))
+            in_i=$(fixthree ${file_i})
         done
     else
-        DO rm -rf $fulln
+        DO rm -rf ${fulln}
     fi
 fi
 echo -e "\e[33mFinished.\e[0m"
diff --git a/lib/libautozip b/lib/libautozip
--- a/lib/libautozip
+++ b/lib/libautozip
@@ -1,75 +1,79 @@
 #!/bin/bash
+# LIBAUTOZIP V2P2
 USESPLIT=false
 REMOVE=false
 #Load libopt
-. $DN/../lib/libisopt && . $DN/../lib/libdo && echo -e "\e[33mlibisopt, libdo loaded.\e[0m"
+{ . $DN/../lib/libisopt && . $DN/../lib/libdo; } && { echo -e "\e[33mlibisopt, libdo loaded.\e[0m"; } || {
+    echo -e "\e[31mFail to load libisopt, libdo.\e[0m"
+    exit 1
+}
 # Check for all compoments: backend.
 function TAR() {
     tar --help &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function GZIP() {
     gzip -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function BGZIP() {
     bgzip -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function PIGZ() {
     pigz -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function XZIP() {
     xz -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function BZIP2() {
     bzip2 -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function Z7() {
     7za -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function ZIP() {
     zip -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function RAR() {
     rar -\? &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function UNZIP() {
     unzip -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function UNRAR() {
     unrar -\? &>>/dev/null
-    echo $?
+    echo ${?}
 }
 function PARALLEL() {
     /usr/bin/parallel -h &>>/dev/null
-    echo $?
+    echo ${?}
 }
 
 function preck() {
     LVL=""
-    CONFN=$(dirname $0)/autozip.conf
+    CONFN=${DN}/../etc/autozip.conf
     USEPARALLEL=false
-    if ! [ -f $CONFN ]; then
+    if ! [ -f ${CONFN} ]; then
         echo -e "\e[31mWARNING: Configure file NOT exist. Will generate one by default value.\e[0m"
-        echo "NOPARALLEL" >$CONFN
-    elif [ -d $CONFN ]; then
+        echo "NOPARALLEL" >${CONFN}
+    elif [ -d ${CONFN} ]; then
         echo -e "\e[31mERROR: Configure file is a directory.\e[0m"
         exit 1
     else
         i=0
         local conf[0]
         while read line; do
-            conf[$i]=$line
-            i=$(($i + 1))
-        done <$CONFN
+            conf[${i}]=${line}
+            i=$((${i} + 1))
+        done <${CONFN}
         unset line
         if [ ${conf[0]} = "PARALLEL" ] && [ $PARALLEL ]; then
             USEPARALLEL=true
@@ -83,7 +87,7 @@ function preck() {
 function autozipck() {
     TAR=$(TAR)
     echo -e "\e[33mStart checking all compoments..."
-    if [ $TAR -eq 0 ]; then
+    if [ ${TAR} -eq 0 ]; then
         echo -e "Checking for 'tar'...\e[32mOK\e[33m"
         availext="tar"
     else
@@ -92,7 +96,7 @@ function autozipck() {
     if [ $(GZIP) -eq 0 ]; then
         echo -e "Checking for 'gzip'...\e[32mOK\e[33m"
         availext="$availext, gz, GZ"
-        if [ $TAR -eq 0 ]; then availext="$availext, tar.gz, tar.GZ, tgz"; fi
+        if [ ${TAR} -eq 0 ]; then availext="$availext, tar.gz, tar.GZ, tgz"; fi
     else
         echo -e "Checking for 'gzip'...\e[31mNO\e[33m"
     fi
@@ -110,14 +114,14 @@ function autozipck() {
     if [ $(XZIP) -eq 0 ]; then
         echo -e "Checking for 'xz'...\e[32mOK\e[33m"
         availext="$availext, xz, lzma, lz"
-        if [ $TAR -eq 0 ]; then availext="$availext, tar.xz, txz, tar.lzma, tlz"; fi
+        if [ ${TAR} -eq 0 ]; then availext="$availext, tar.xz, txz, tar.lzma, tlz"; fi
     else
         echo -e "Checking for 'xz'...\e[31mNO\e[33m"
     fi
     if [ $(BZIP2) -eq 0 ]; then
         echo -e "Checking for 'bzip2'...\e[32mOK\e[33m"
         availext="$availext, bz2"
-        if [ $TAR -eq 0 ]; then availext="$availext, tar.bz2, tbz"; fi
+        if [ ${TAR} -eq 0 ]; then availext="$availext, tar.bz2, tbz"; fi
     else
         echo -e "Checking for 'bzip2'...\e[31mNO\e[33m"
     fi
@@ -155,14 +159,14 @@ function autozipck() {
         echo -e "Checking for 'parallel' in /usr/bin...\e[31mNO\e[33m"
     fi
     echo -e "Available extension name on your computer:\n$availext"
-    echo "Configure file $CONFN are as follows:"
-    echo -e "=====Begin $CONFN=====\e[0m"
-    cat $CONFN
-    echo -e "\e[33m=====End   $CONFN=====\e[0m"
+    echo "Configure file ${CONFN} are as follows:"
+    echo -e "=====Begin ${CONFN}=====\e[0m"
+    cat ${CONFN}
+    echo -e "\e[33m=====End   ${CONFN}=====\e[0m"
 }
 #Modify Filenames
 function mfn() {
-    echo $* | sed -e "s,(,\\\\\(,g" | sed -e "s,),\\\\\),g" | sed -e "s,\[,\\\\\[,g" | sed -e "s,\],\\\\\],g" | sed -e "s,<,\\\\\<,g" | sed -e "s,>,\\\\\>,g" | sed -e "s,{,\\\\\{,g" | sed -e "s,},\\\\\},g"
+    echo ${*} | sed -e "s,(,\\\\\(,g" | sed -e "s,),\\\\\),g" | sed -e "s,\[,\\\\\[,g" | sed -e "s,\],\\\\\],g" | sed -e "s,<,\\\\\<,g" | sed -e "s,>,\\\\\>,g" | sed -e "s,{,\\\\\{,g" | sed -e "s,},\\\\\},g"
 }
 #Makt temporaty resources
 function mktmp() {
@@ -172,48 +176,23 @@ function mktmp() {
 }
 # Check opt
 function ppopt() {
-    for opt in $@; do
-        case $opt in
-        "-s" | "--split")
-            USESPLIT=true
-            case $ext in
-            "rar" | "zip" | "7z")
-                SPLIT=1024m
-                ;;
-            *)
-                SPLIT=1G
-                ;;
-            esac
-            ;;
-        -s\:*)
-            USESPLIT=true
-            SPLIT=${opt:3}
-            ;;
-        --split\:*)
-            USESPLIT=true
-            SPLIT=${opt:8}
-            ;;
-        esac
-    done
-    for opt in $@; do
+    for opt in "${@}"; do
         if isopt $opt; then
             case $opt in
             "-h" | "--help")
-                if [ -f $DN/autozip.Usage ]; then
-                    cat $DN/autozip.Usage
-                    exit 0
-                else
-                    echo -e "\e[31mERROR: $DN/autozip.Usage not found!\e[0m"
-                    exit 1
-                fi
+                yldoc autozip
+                exit 0
                 ;;
             "-v" | "--version")
-                echo "Version 2 patch 1"
+                echo "Version 2 patch 2"
                 exit 0
                 ;;
             --force-parallel\:*)
                 PP=${opt:17}
-                if [ $($PP -h &>>/dev/null;echo $?) -eq 0 ]; then
+                if [ $(
+                    $PP -h &>>/dev/null
+                    echo ${?}
+                ) -eq 0 ]; then
                     USEPARALLEL=true
                     echo -e "\e[33mWill use GNU Parallel in '$PP'.\e[0m"
                 else
@@ -228,11 +207,25 @@ function ppopt() {
                 echo -e "\e[33mWARNING: Will remove $fn if success.\e[0m"
                 REMOVE=true
                 ;;
-            "-s" | "--split" | -s\:* | --split\:*)
-                if ! ${ISAUTOZIP}; then
-                    echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
-                    exit 1
-                fi
+
+            "-s" | "--split")
+                USESPLIT=true
+                case ${ext} in
+                "rar" | "zip" | "7z")
+                    SPLIT=1024m
+                    ;;
+                *)
+                    SPLIT=1G
+                    ;;
+                esac
+                ;;
+            -s\:*)
+                USESPLIT=true
+                SPLIT=${opt:3}
+                ;;
+            --split\:*)
+                USESPLIT=true
+                SPLIT=${opt:8}
                 ;;
             *)
                 echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
