azman added

diff --git a/bin/autounzip b/bin/autounzip
--- a/bin/autounzip
+++ b/bin/autounzip
@@ -1,5 +1,5 @@
 #!/bin/bash
-# AUTOUNZIP V2P3
+# AUTOUNZIP V2P4
 # ============ Functions ============
 DN=$(dirname ${0})
 exec 1>&2
@@ -65,7 +65,7 @@ echo -e "\e[33mCopyright (C) 2019-2020 YU Zhejian\e[0m"
 preck
 # ============ Possess options ============
 ISAOTOZIP=false
-ppopt $@
+ppopt ${@}
 # ============ Possess arguments ============
 STDI=(${STDS})
 fulln=${STDI[0]}
@@ -89,7 +89,7 @@ if [ -e ${fn} ]; then
     echo -e "\e[31mWARNING: ${fn} exists! Will rename ${fn} as ${fn}.bak.\e[0m"
     DO mv -f ${fn} ${fn}.bak
 fi
-echo -e "\e[33mReceived: $0 ${fulln} $OPT ==>Extension=${ext}\e[0m"
+echo -e "\e[33mReceived: ${0} ${fulln} ${OPT} ==>Extension=${ext}\e[0m"
 # ============ Makt tmp ============
 mktmp
 # ============ Start Compressing ============
@@ -116,6 +116,10 @@ case ${ext} in
 "tar.gz" | "tgz" | "tar.GZ") # ============ tgz ============
     if ! [ $(GZIP) -eq 0 ]; then
         echo -e "\e[31mERROR: GZip NO exist!\e[0m"
+        exit 1
+    fi
+        if ! [ $(TAR) -eq 0 ]; then
+        echo -e "\e[31mERROR: GNU Tar NO exist!\e[0m"
         exit 1
     fi
     if ${USESPLIT}; then
diff --git a/lib/libautozip b/lib/libautozip
--- a/lib/libautozip
+++ b/lib/libautozip
@@ -1,5 +1,5 @@
 #!/bin/bash
-# LIBAUTOZIP V2P3
+# LIBAUTOZIP V2P4
 USESPLIT=false
 REMOVE=false
 #Load libopt
@@ -177,14 +177,14 @@ function mktmp() {
 # Check opt
 function ppopt() {
     for opt in "${@}"; do
-        if isopt $opt; then
-            case $opt in
+        if isopt ${opt}; then
+            case ${opt} in
             "-h" | "--help")
                 yldoc autozip
                 exit 0
                 ;;
             "-v" | "--version")
-                echo "Version 2 patch 3"
+                echo "Version 2 patch 4"
                 exit 0
                 ;;
             --force-parallel\:*)
@@ -209,6 +209,10 @@ function ppopt() {
                 ;;
 
             "-s" | "--split")
+            if ! ${ISAOTOZIP};then
+              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                exit 1
+                fi
                 USESPLIT=true
                 case ${ext} in
                 "rar" | "zip" | "7z")
@@ -220,21 +224,29 @@ function ppopt() {
                 esac
                 ;;
             -s\:*)
+                          if ! ${ISAOTOZIP};then
+              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                exit 1
+                fi
                 USESPLIT=true
                 SPLIT=${opt:3}
                 ;;
             --split\:*)
+                          if ! ${ISAOTOZIP};then
+              echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+                exit 1
+                fi
                 USESPLIT=true
                 SPLIT=${opt:8}
                 ;;
             *)
-                echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
+                echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
                 exit 1
                 ;;
             esac
-            OPT="$OPT $opt"
+            OPT="${OPT} ${opt}"
         else
-            STDS="$STDS $opt"
+            STDS="${STDS} ${opt}"
         fi
     done
 }
