Tab fixed

diff --git a/bin/azman b/bin/azman
--- a/bin/azman
+++ b/bin/azman
@@ -11,11 +11,11 @@ ppopt "${@}"
 azcmd=${STDS[0]:-}
 unset STDS[0]
 if [ -z "${azcmd}" ]; then
-    autozipck
-    exit 0
+	autozipck
+	exit 0
 elif [ -f "${DN}"/exec/azman_"${azcmd}".sh ];then
-    . "${DN}"/exec/azman_"${azcmd}".sh
+	. "${DN}"/exec/azman_"${azcmd}".sh
 else
-    echo -e "\033[31mERROR: subcommand '${azcmd}' invalid! \033[0m"
-    exit 1
+	echo -e "\033[31mERROR: subcommand '${azcmd}' invalid! \033[0m"
+	exit 1
 fi
diff --git a/bin/bhs b/bin/bhs
--- a/bin/bhs
+++ b/bin/bhs
@@ -9,38 +9,38 @@ echo -e "Copyright (C) 2019-2020 YU Zhejian\033[0m"
 . "${DN}"/../lib/libisopt
 STDS=""
 for opt in "${@}"; do
-    if isopt "${opt}"; then
-        case "${opt}" in
-        "-h" | "--help")
-            yldoc bhs
-            exit 0
-            ;;
-        "-v" | "--version")
-            echo "Version 1 Emergency Patch 5"
-            exit 0
-            ;;
-        --more\:*)
-            more="${opt:7}"
-            if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
-                echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
-                more="${mymore}"
-            else
-                echo -e "\033[33mWill use '${more}' as More.\033[0m"
-            fi
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS="${STDS}${opt} "
-    fi
+	if isopt "${opt}"; then
+		case "${opt}" in
+		"-h" | "--help")
+			yldoc bhs
+			exit 0
+			;;
+		"-v" | "--version")
+			echo "Version 1 Emergency Patch 5"
+			exit 0
+			;;
+		--more\:*)
+			more="${opt:7}"
+			if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
+				echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
+				more="${mymore}"
+			else
+				echo -e "\033[33mWill use '${more}' as More.\033[0m"
+			fi
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS="${STDS}${opt} "
+	fi
 done
 STDS=$(echo "${STDS}"|"${mysed}" "s/ $//")
 if [ -n "${STDS}" ]; then
-    echo \"${STDS}\"
-    "${mycat}" -n ~/.bash_history | "${mygrep}" --color=auto -- "${STDS}" | "${more}"
+	echo \"${STDS}\"
+	"${mycat}" -n ~/.bash_history | "${mygrep}" --color=auto -- "${STDS}" | "${more}"
 else
-    "${mycat}" -n ~/.bash_history | "${more}"
+	"${mycat}" -n ~/.bash_history | "${more}"
 fi
diff --git a/bin/lcman b/bin/lcman
--- a/bin/lcman
+++ b/bin/lcman
@@ -6,14 +6,14 @@ DN="$(readlink -f "$(dirname "${0}")")"
 echo -e "\033[33mYuZJLab LiveChat Manager"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\033[0m"
 if ! [[ "$("${mymore}" --version 2>&1||true)" =~ .*"util-linux".* ]]; then
-    echo -e "\033[31mWARNING: Will use ${mycat} as more.\033[0m"
-    mymore="${mycat}"
+	echo -e "\033[31mWARNING: Will use ${mycat} as more.\033[0m"
+	mymore="${mycat}"
 fi
 more="${mymore}"
 LVCD="${DN}/../var/livechat.d"
 if [ ! -e "${LVCD}"/MESSAGES ]; then
-    echo -e "\033[31mERROR: livechat.d/MESSAGES not exist.\033[0m"
-    exit 1
+	echo -e "\033[31mERROR: livechat.d/MESSAGES not exist.\033[0m"
+	exit 1
 fi
 OLD_IFS="${IFS}"
 IFS=";"
@@ -24,103 +24,103 @@ sf=()
 sm=()
 se=()
 for opt in "${@}"; do
-    if isopt "${opt}"; then
-        case "${opt}" in
-        "-v" | "--version")
-            echo -e "\033[33mVersion 3 Emergency Patch 5, compatiable with LiveChat Version 1 & 2.\033[0m"
-            exit 0
-            ;;
-        "-h" | "--help")
-            yldoc lcman
-            exit 0
-            ;;
-        --more\:*)
-            more="${opt:7}"
-            if [ $("${more}" --help &>/dev/null;echo ${?}) -eq 127 ]; then
-                echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
-                more="${mymore}"
-            else
-                echo -e "\033[33mWill use '${more}' as More.\033[0m"
-            fi
-            ;;
-        -f\:*)
-            sf=(${sf[@]} ${opt:3})
-            ;;
-        -m\:*)
-            sm=(${sm[@]} ${opt:3})
-            ;;
-        --from\:*)
-            sf=(${sf[@]} ${opt:7})
-            ;;
-        --message\:*)
-            sm=(${sm[@]} ${opt:10})
-            ;;
-        -e\:*)
-            se=(${se[@]} ${opt:3})
-            ;;
-        --exclude\:*)
-            se=(${se[@]} ${opt:10})
-            ;;
-        "-s" | "--exclude-system")
-            se=(${se[@]} "SYSTEM")
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS=("${STDS[@]}" "${opt}")
-    fi
+	if isopt "${opt}"; then
+		case "${opt}" in
+		"-v" | "--version")
+			echo -e "\033[33mVersion 3 Emergency Patch 5, compatiable with LiveChat Version 1 & 2.\033[0m"
+			exit 0
+			;;
+		"-h" | "--help")
+			yldoc lcman
+			exit 0
+			;;
+		--more\:*)
+			more="${opt:7}"
+			if [ $("${more}" --help &>/dev/null;echo ${?}) -eq 127 ]; then
+				echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
+				more="${mymore}"
+			else
+				echo -e "\033[33mWill use '${more}' as More.\033[0m"
+			fi
+			;;
+		-f\:*)
+			sf=(${sf[@]} ${opt:3})
+			;;
+		-m\:*)
+			sm=(${sm[@]} ${opt:3})
+			;;
+		--from\:*)
+			sf=(${sf[@]} ${opt:7})
+			;;
+		--message\:*)
+			sm=(${sm[@]} ${opt:10})
+			;;
+		-e\:*)
+			se=(${se[@]} ${opt:3})
+			;;
+		--exclude\:*)
+			se=(${se[@]} ${opt:10})
+			;;
+		"-s" | "--exclude-system")
+			se=(${se[@]} "SYSTEM")
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS=("${STDS[@]}" "${opt}")
+	fi
 done
 echo -e "\033[33mReading Databases...\033[0m"
 i=0
 while read line; do
-    msg_tmp=(${line})
-    f[${i}]="${msg_tmp[1]}"
-    m[${i}]="${msg_tmp[2]}"
-    uf[${i}]=false
-    um[${i}]=false
-    unset msg_tmp
-    i=$(($i + 1))
+	msg_tmp=(${line})
+	f[${i}]="${msg_tmp[1]}"
+	m[${i}]="${msg_tmp[2]}"
+	uf[${i}]=false
+	um[${i}]=false
+	unset msg_tmp
+	i=$(($i + 1))
 done <"${LVCD}"/MESSAGES
 echo -e "\033[33mFiltering...\033[0m"
 if [ ${#sf[@]} -eq 0 ]; then
-    for ((n = 0; n <= i; n++)); do
-        uf[${n}]=true
-    done
+	for ((n = 0; n <= i; n++)); do
+		uf[${n}]=true
+	done
 else
-    for item in "${sf[@]}"; do
-        for ((n = 0; n <= i - 1; n++)); do
-            [[ ${f[${n}]} == *${item}* ]] && uf[${n}]=true || true
-        done
-    done
+	for item in "${sf[@]}"; do
+		for ((n = 0; n <= i - 1; n++)); do
+			[[ ${f[${n}]} == *${item}* ]] && uf[${n}]=true || true
+		done
+	done
 fi
 if ! [ ${#se[@]} -eq 0 ]; then
-    for item in "${se[@]}"; do
-        for ((n = 0; n <= i - 1; n++)); do
-            [[ ${f[${n}]} == *${item}* ]] && uf[${n}]=false || true
-        done
-    done
+	for item in "${se[@]}"; do
+		for ((n = 0; n <= i - 1; n++)); do
+			[[ ${f[${n}]} == *${item}* ]] && uf[${n}]=false || true
+		done
+	done
 fi
 if [ ${#sm[@]} -eq 0 ]; then
-    for ((n = 0; n <= i; n++)); do
-        um[${n}]=true
-    done
+	for ((n = 0; n <= i; n++)); do
+		um[${n}]=true
+	done
 else
-    for item in "${sm[@]}"; do
-        for ((n = 0; n <= i - 1; n++)); do
-            [[ ${m[${n}]} == *${item}* ]] && um[${n}]=true || true
-        done
-    done
+	for item in "${sm[@]}"; do
+		for ((n = 0; n <= i - 1; n++)); do
+			[[ ${m[${n}]} == *${item}* ]] && um[${n}]=true || true
+		done
+	done
 fi
 n=0
 while read line; do
-    if ${uf[${n}]} && ${um[${n}]}; then
-        msg_tmp=(${line})
-        echo -e "\033[31m[${msg_tmp[0]}]\033[0m \033[36m[${msg_tmp[1]}]\033[0m ${msg_tmp[2]}" >>"${tmpfff}"
-    fi
-    n=$((n + 1))
+	if ${uf[${n}]} && ${um[${n}]}; then
+		msg_tmp=(${line})
+		echo -e "\033[31m[${msg_tmp[0]}]\033[0m \033[36m[${msg_tmp[1]}]\033[0m ${msg_tmp[2]}" >>"${tmpfff}"
+	fi
+	n=$((n + 1))
 done <${LVCD}/MESSAGES
 "${mycat}" "${tmpfff}" | "${mysort}" | "${more}"
 IFS=${OLD_IFS}
diff --git a/bin/libdoman_upgrade b/bin/libdoman_upgrade
--- a/bin/libdoman_upgrade
+++ b/bin/libdoman_upgrade
@@ -3,19 +3,19 @@ set -ue
 DN="$(readlink -f "$(dirname "${0}")")"
 . "${DN}"/../etc/path.sh
 for fn in "${@}"; do
-    if ! [ -f "${fn}" ]; then
-        echo -e "\033[31mERROR! Invalid file '${fn}' will be ignored.\033[0m"
-        continue
-    fi
-    "${mycat}" "${fn}" | while read line; do
-        if [[ "${line}" =~ "LIBDO STARTED AT"* ]] || [[ "${line}" =~ "LIBDO STOPPED AT"* ]]; then
-            mytime="$(echo ${line:17} | "${mysed}" "s/.$//")"
-            [[ "$(date --version 2>&1 || true)" =~ "GNU" ]] && newtime="$(date -d "${mytime}" +'%Y-%m-%d %H:%M:%S')" || newtime="$(date -j -f '%a %b %d %T %Z %Y' "${mytime}" +'%Y-%m-%d %H:%M:%S')"
-            echo "${line:0:17}${newtime}" >>"${fn}.2"
-        elif [[ "${line}" =~ "LIBDO FAILED, GOT"* ]]||[[ "${line}" =~ "LIBDO EXITED SUCCESSFULLY"* ]]; then
-            echo "${line}" | "${mysed}" "s/.$//" >>"${fn}.2"
-        else
-            echo "${line}" >>"${fn}.2"
-        fi
-    done
+	if ! [ -f "${fn}" ]; then
+		echo -e "\033[31mERROR! Invalid file '${fn}' will be ignored.\033[0m"
+		continue
+	fi
+	"${mycat}" "${fn}" | while read line; do
+		if [[ "${line}" =~ "LIBDO STARTED AT"* ]] || [[ "${line}" =~ "LIBDO STOPPED AT"* ]]; then
+			mytime="$(echo ${line:17} | "${mysed}" "s/.$//")"
+			[[ "$(date --version 2>&1 || true)" =~ "GNU" ]] && newtime="$(date -d "${mytime}" +'%Y-%m-%d %H:%M:%S')" || newtime="$(date -j -f '%a %b %d %T %Z %Y' "${mytime}" +'%Y-%m-%d %H:%M:%S')"
+			echo "${line:0:17}${newtime}" >>"${fn}.2"
+		elif [[ "${line}" =~ "LIBDO FAILED, GOT"* ]]||[[ "${line}" =~ "LIBDO EXITED SUCCESSFULLY"* ]]; then
+			echo "${line}" | "${mysed}" "s/.$//" >>"${fn}.2"
+		else
+			echo "${line}" >>"${fn}.2"
+		fi
+	done
 done
diff --git a/bin/livechat b/bin/livechat
--- a/bin/livechat
+++ b/bin/livechat
@@ -4,33 +4,33 @@ set -ue
 DN="$(readlink -f "$(dirname "${0}")")"
 . "${DN}"/../etc/path.sh
 function sdmess() {
-    echo "$(date +%Y-%m-%d,%H:%M:%S);${1};${MESS_SD}" >>MESSAGES
+	echo "$(date +%Y-%m-%d,%H:%M:%S);${1};${MESS_SD}" >>MESSAGES
 }
 function F_REC() {
-    while true; do
-    #echo a
-        IFS=""
-        sleep 1
-        local arr=$(wc -l MESSAGES | awk '{print $1}')
-        local en=$((${arr} - ${M_R}))
-        if [ ${en} -ne 0 ]; then
-            echo -ne "\007"
-            "${mytail}" -n $((${arr} - ${M_R})) MESSAGES >"URM_${LCUN}"
-            local M_R=${arr}
-            IFS=";"
-            while read line; do
-                local M_A=(${line})
-                echo -e "\033[31m[${M_A[0]}]\033[0m \033[36m[${M_A[1]}]\033[0m ${M_A[2]}"
-            done <"URM_${LCUN}"
-        fi
-    done
+	while true; do
+	#echo a
+		IFS=""
+		sleep 1
+		local arr=$(wc -l MESSAGES | awk '{print $1}')
+		local en=$((${arr} - ${M_R}))
+		if [ ${en} -ne 0 ]; then
+			echo -ne "\007"
+			"${mytail}" -n $((${arr} - ${M_R})) MESSAGES >"URM_${LCUN}"
+			local M_R=${arr}
+			IFS=";"
+			while read line; do
+				local M_A=(${line})
+				echo -e "\033[31m[${M_A[0]}]\033[0m \033[36m[${M_A[1]}]\033[0m ${M_A[2]}"
+			done <"URM_${LCUN}"
+		fi
+	done
 }
 OLD_IFS="${IFS}"
 LVCD="${DN}/../var/livechat.d"
 mkdir -p "${LVCD}"
 if [ ! -e "${LVCD}"/LCONLINE ]; then
-    echo -e "\033[31mWARNING: livechat.d/LCONLINE not exist.\033[0m"
-    touch "${LVCD}"/LCONLINE
+	echo -e "\033[31mWARNING: livechat.d/LCONLINE not exist.\033[0m"
+	touch "${LVCD}"/LCONLINE
 fi
 cd "${LVCD}"
 unset LVCD
@@ -39,38 +39,38 @@ echo -e "Copyright (C) 2019-2020 YU Zhejian\033[0m"
 . "${DN}"/../lib/libisopt
 STDS=""
 for opt in "${@}"; do
-    if isopt ${opt}; then
-        case ${opt} in
-        "-h" | "--help")
-            yldoc livechat
-            exit 0
-            ;;
-        "-v" | "--version")
-            echo "Version 1 Emergency Patch 7"
-            exit 0
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS="${opt}"
-    fi
+	if isopt ${opt}; then
+		case ${opt} in
+		"-h" | "--help")
+			yldoc livechat
+			exit 0
+			;;
+		"-v" | "--version")
+			echo "Version 1 Emergency Patch 7"
+			exit 0
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS="${opt}"
+	fi
 done
 
 if [ -z "${STDS}" ]; then
-    echo -e "\033[33mPlease key in your name/roomnumber:\033[0m"
-    echo -e "\033[33mUse Ctrl-C to exit\033[0m"
-    read LCUN
+	echo -e "\033[33mPlease key in your name/roomnumber:\033[0m"
+	echo -e "\033[33mUse Ctrl-C to exit\033[0m"
+	read LCUN
 else
-    LCUN="${STDS}"
+	LCUN="${STDS}"
 fi
 while read line;do
-    if [ "${line}" = "${LCUN}" ];then
-    echo -e "\033[31mERROR: There's a user with the same name.\033[0m"
-    exit 1
-    fi
+	if [ "${line}" = "${LCUN}" ];then
+	echo -e "\033[31mERROR: There's a user with the same name.\033[0m"
+	exit 1
+	fi
 done < LCONLINE
 unset BOOLONLINE
 echo "${LCUN}" >>LCONLINE
@@ -84,19 +84,19 @@ export M_R=0
 pid_rec=${!}
 echo -e "\033[33mPID of reciever: ${pid_rec}.\033[0m"
 while true; do
-    read MESS_SD
-    if [ "${MESS_SD}" != "logout" ]; then
-        sdmess "${LCUN}"
-        printf "\033[1A"
-    else
-        MESS_SD="${LCUN} had quitted."
-        sdmess "SYSTEM"
-        kill -9 ${pid_rec} &>>/dev/null
-        "${mycat}" LCONLINE |"${mygrep}" -v "^${LCUN}$" >tmp
-        "${mymv}" tmp LCONLINE
-        "${myrm}" "URM_${LCUN}"
-        echo -e "\033[33mThanks for using this system.\033[0m"
-        IFS="${OLD_IFS}"
-        exit 0
-    fi
+	read MESS_SD
+	if [ "${MESS_SD}" != "logout" ]; then
+		sdmess "${LCUN}"
+		printf "\033[1A"
+	else
+		MESS_SD="${LCUN} had quitted."
+		sdmess "SYSTEM"
+		kill -9 ${pid_rec} &>>/dev/null
+		"${mycat}" LCONLINE |"${mygrep}" -v "^${LCUN}$" >tmp
+		"${mymv}" tmp LCONLINE
+		"${myrm}" "URM_${LCUN}"
+		echo -e "\033[33mThanks for using this system.\033[0m"
+		IFS="${OLD_IFS}"
+		exit 0
+	fi
 done
diff --git a/bin/manls b/bin/manls
--- a/bin/manls
+++ b/bin/manls
@@ -16,56 +16,56 @@ unset duplicated_path
 IFS=''
 STDS=()
 for opt in "${@}"; do
-    if isopt "${opt}"; then
-        case "${opt}" in
-        "-h" | "--help")
-            yldoc pls
-            exit 0
-            ;;
-        "-v" | "--version")
-            echo "Version 1 Patch 1 in Bash"
-            exit 0
-            ;;
-        "-l" | "--list")
-            echo ${valid_path} | tr ':' '\n'
-            unset valid_path
-            exit 0
-            ;;
-        --more\:*)
-            more=$"{opt:7}"
-            if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
-                echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
-                more="${mymore}"
-            else
-                echo -e "\033[33mWill use '${more}' as More.\033[0m"
-            fi
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS=(${STDS[@]} "${opt}")
-    fi
+	if isopt "${opt}"; then
+		case "${opt}" in
+		"-h" | "--help")
+			yldoc pls
+			exit 0
+			;;
+		"-v" | "--version")
+			echo "Version 1 Patch 1 in Bash"
+			exit 0
+			;;
+		"-l" | "--list")
+			echo ${valid_path} | tr ':' '\n'
+			unset valid_path
+			exit 0
+			;;
+		--more\:*)
+			more=$"{opt:7}"
+			if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
+				echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
+				more="${mymore}"
+			else
+				echo -e "\033[33mWill use '${more}' as More.\033[0m"
+			fi
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS=(${STDS[@]} "${opt}")
+	fi
 done
 unset invalid_path valid_path
 tmpf="$(mktemp -t pls.XXXXXX)"
 echo -e "\033[33mReading database...\033[0m"
 for dir in "${eachpath[@]}"; do
-    "${myls}" -1 -F "${dir}" | "${mysed}" "s;^;$(echo "${dir}")/;" | "${mygrep}" man[^/]*/$ | while read line; do
-        "${myls}" -1 -F "${line}"|"${mysed}" "s;.gz;;"|"${mysed}" "s;^;$(echo "${line}");" >>"${tmpf}"
-    done
+	"${myls}" -1 -F "${dir}" | "${mysed}" "s;^;$(echo "${dir}")/;" | "${mygrep}" man[^/]*/$ | while read line; do
+		"${myls}" -1 -F "${line}"|"${mysed}" "s;.gz;;"|"${mysed}" "s;^;$(echo "${line}");" >>"${tmpf}"
+	done
 done
 if [ ${#STDS[@]} -eq 0 ]; then
-    "${mycat}" "${tmpf}" | "${more}"
+	"${mycat}" "${tmpf}" | "${more}"
 else
-    IFS=''
-    grepstr=''
-    for fn in "${STDS[@]}"; do
-        grepstr="${grepstr} -e ${fn}"
-    done
-    eval "${mycat}" \"${tmpf}\"\|"${mygrep}" "${grepstr}"\|"${more}"
+	IFS=''
+	grepstr=''
+	for fn in "${STDS[@]}"; do
+		grepstr="${grepstr} -e ${fn}"
+	done
+	eval "${mycat}" \"${tmpf}\"\|"${mygrep}" "${grepstr}"\|"${more}"
 fi
 rm "${tmpf}"
 IFS="${oldifs}"
diff --git a/bin/pss b/bin/pss
--- a/bin/pss
+++ b/bin/pss
@@ -9,50 +9,50 @@ cd "$(readlink -f "$(dirname "${0}")")"
 more="${mymore}"
 STDS=()
 for opt in "${@}"; do
-    if isopt ${opt}; then
-        case ${opt} in
-        "-h" | "--help")
-            yldoc pss
-            exit 0
-            ;;
-        "-v" | "--version")
-            echo "Version 1 patch 8"
-            exit 0
-            ;;
-        --more\:*)
-            more="${opt:7}"
-            if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
-                echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
-                more="${mymore}"
-            else
-                echo -e "\033[33mWill use '${more}' as More.\033[0m"
-            fi
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS=("${STDS[@]}" "${opt}")
-    fi
+	if isopt ${opt}; then
+		case ${opt} in
+		"-h" | "--help")
+			yldoc pss
+			exit 0
+			;;
+		"-v" | "--version")
+			echo "Version 1 patch 8"
+			exit 0
+			;;
+		--more\:*)
+			more="${opt:7}"
+			if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
+				echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
+				more="${mymore}"
+			else
+				echo -e "\033[33mWill use '${more}' as More.\033[0m"
+			fi
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS=("${STDS[@]}" "${opt}")
+	fi
 done
 psstmp=$(mktemp -t psstmp.XXXXXX)
 pssstmp=$(mktemp -t psstmp.XXXXXX)
 if ! "${myps}" --version &>> /dev/null;then
-    "${myps}" -a -l &>"${psstmp}"
+	"${myps}" -a -l &>"${psstmp}"
 elif [[ $("${myps}" --version) == *cygwin* ]]; then
-    "${myps}" -W &>"${psstmp}"
+	"${myps}" -W &>"${psstmp}"
 else
-    "${myps}" -A all &>"${psstmp}"
+	"${myps}" -A all &>"${psstmp}"
 fi
 if [ ${#STDS[@]} -eq 0 ]; then
-    "${mycat}" "${psstmp}" | "${more}"
+	"${mycat}" "${psstmp}" | "${more}"
 else
-    ${myhead} -n 1 ${psstmp}
-    for fn in "${STDS[@]}"; do
-        "${mycat}" "${psstmp}" | "${mygrep}" -- "${fn}" >>"${pssstmp}"
-    done
-    "${mycat}" "${pssstmp}" | "${more}"
+	${myhead} -n 1 ${psstmp}
+	for fn in "${STDS[@]}"; do
+		"${mycat}" "${psstmp}" | "${mygrep}" -- "${fn}" >>"${pssstmp}"
+	done
+	"${mycat}" "${pssstmp}" | "${more}"
 fi
 "${myrm}" "${psstmp}" "${pssstmp}"
diff --git a/bin/yldoc b/bin/yldoc
--- a/bin/yldoc
+++ b/bin/yldoc
@@ -9,58 +9,58 @@ echo -e "Copyright (C) 2019-2020 YU Zhejian\033[0m"
 more="${mymore}"
 STDS=()
 for opt in "${@}"; do
-    if isopt "${opt}"; then
-        case "${opt}" in
-        "-h" | "--help")
-            yldoc yldoc
-            exit 0
-            ;;
-        "-v" | "--version")
-            echo "Version 1 Patch 6"
-            exit 0
-            ;;
-        --more\:*)
-            more="${opt:7}"
-            if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
-                echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
-                more="${mymore}"
-            else
-                echo -e "\033[33mWill use '${more}' as More.\033[0m"
-            fi
-            ;;
-        "-l" | "--list")
-            echo -e "\033[33mReading database...\033[0m"
-            "${myls}" -1 "${DN}"/../doc | "${mysort}" | "${mysed}" 's/.usage//' | "${more}"
-            exit 0
-            ;;
-        *)
-            echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
-            exit 1
-            ;;
-        esac
-    else
-        STDS=("${STDS[@]}" "${opt}")
-    fi
+	if isopt "${opt}"; then
+		case "${opt}" in
+		"-h" | "--help")
+			yldoc yldoc
+			exit 0
+			;;
+		"-v" | "--version")
+			echo "Version 1 Patch 6"
+			exit 0
+			;;
+		--more\:*)
+			more="${opt:7}"
+			if $("${more}" --help &>/dev/null;echo ${?}) -eq 127; then
+				echo -e "\033[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\033[0m"
+				more="${mymore}"
+			else
+				echo -e "\033[33mWill use '${more}' as More.\033[0m"
+			fi
+			;;
+		"-l" | "--list")
+			echo -e "\033[33mReading database...\033[0m"
+			"${myls}" -1 "${DN}"/../doc | "${mysort}" | "${mysed}" 's/.usage//' | "${more}"
+			exit 0
+			;;
+		*)
+			echo -e "\033[31mERROR: Option '${opt}' invalid.\033[0m"
+			exit 1
+			;;
+		esac
+	else
+		STDS=("${STDS[@]}" "${opt}")
+	fi
 done
 if [ ${#STDS[@]} -eq 0 ]; then
-    yldoc yldoc
-    exit 0
+	yldoc yldoc
+	exit 0
 fi
 if [ -f "${DN}"/../etc/yldoc.conf ]; then
-    while read line; do
-        li=(${line})
-        for ((i = 0; i < ${#STDS[@]}; i++)); do
-            if [ ${STDS[${i}]} = ${li[0]} ]; then
-                STDS[${i}]=${li[1]}
-            fi
-        done
-    done <"${DN}"/../etc/yldoc.conf
+	while read line; do
+		li=(${line})
+		for ((i = 0; i < ${#STDS[@]}; i++)); do
+			if [ ${STDS[${i}]} = ${li[0]} ]; then
+				STDS[${i}]=${li[1]}
+			fi
+		done
+	done <"${DN}"/../etc/yldoc.conf
 fi
 for fn in "${STDS[@]}"; do
-    if [ -f "${DN}"/../doc/"${fn}".usage ]; then
-        "${mycat}" "${DN}"/../doc/"${fn}".usage | "${more}"
-    else
-        echo -e "\033[31mERROR: ${DN}/../doc/${fn}.usage not found! \033[0m"
-        exit 1
-    fi
+	if [ -f "${DN}"/../doc/"${fn}".usage ]; then
+		"${mycat}" "${DN}"/../doc/"${fn}".usage | "${more}"
+	else
+		echo -e "\033[31mERROR: ${DN}/../doc/${fn}.usage not found! \033[0m"
+		exit 1
+	fi
 done
