Some File-system updates, adoc2usage rewritten in Python

diff --git a/bin/bhs b/bin/bhs
--- a/bin/bhs
+++ b/bin/bhs
@@ -4,7 +4,10 @@ DN=$(dirname ${0})
 more="more"
 echo -e "\e[33mYuZJLab Bash History Searcher"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\e[0m"
-{ . $DN/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || { echo -e "\e[31mFail to load libisopt.\e[0m";exit 1; }
+{ . ${DN}/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || {
+    echo -e "\e[31mFail to load libisopt.\e[0m"
+    exit 1
+}
 for opt in "${@}"; do
     if isopt ${opt}; then
         case ${opt} in
@@ -30,7 +33,7 @@ for opt in "${@}"; do
 done
 if [ -n "${STDS}" ]; then
     echo \"${STDS}\"
-    cat -n ~/.bash_history | grep --color=auto -- ${STDS} | $more
+    cat -n ~/.bash_history | grep --color=auto -- ${STDS} | ${more}
 else
-    cat -n ~/.bash_history | $more
+    cat -n ~/.bash_history | ${more}
 fi
