More commands added.

diff --git a/bin/lcman b/bin/lcman
--- a/bin/lcman
+++ b/bin/lcman
@@ -1,8 +1,10 @@
 #!/usr/bin/env bash
-# LCMAN V3P3
+# LCMAN V3P4
+set -ue
+DN=$(dirname ${0})
+. "${DN}"/../etc/path.sh
 echo -e "\e[33mYuZJLab LiveChat Manager"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\e[0m"
-DN=$(dirname ${0})
 LVCD="${DN}/../var/livechat.d"
 if [ ! -e ${LVCD}/MESSAGES ]; then
     echo -e "\e[31mERROR: livechat.d/MESSAGES not exist.\e[0m"
@@ -10,17 +12,18 @@ if [ ! -e ${LVCD}/MESSAGES ]; then
 fi
 OLD_IFS="${IFS}"
 IFS=";"
-tmpfff=$(mktemp -t lcman.XXXXXX)
-{ . $DN/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || {
-    echo -e "\e[31mFail to load libisopt.\e[0m"
-    exit 1
-}
-more="more"
+tmpfff="$(mktemp -t lcman.XXXXXX)"
+. "${DN}"/../lib/libisopt
+more="${mymore}"
+STDS=''
+sf=()
+sm=()
+se=()
 for opt in "${@}"; do
-    if isopt ${opt}; then
-        case ${opt} in
-        "-v"|"--version")
-            echo -e "\e[33mVersion 3 patch 3, compatiable with LiveChat Version 1 & 2.\e[0m"
+    if isopt "${opt}"; then
+        case "${opt}" in
+        "-v" | "--version")
+            echo -e "\e[33mVersion 3 patch 4, compatiable with LiveChat Version 1 & 2.\e[0m"
             exit 0
             ;;
         "-h" | "--help")
@@ -28,7 +31,13 @@ for opt in "${@}"; do
             exit 0
             ;;
         --more\:*)
-            more=${opt:7}
+            more="${opt:7}"
+            if ! "${more}" --help &>/dev/null; then
+                echo -e "\e[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\e[0m"
+                more="${mymore}"
+            else
+                echo -e "\e[33mWill use '${more}' as More.\e[0m"
+            fi
             ;;
         -f\:*)
             sf=(${sf[@]} ${opt:3})
@@ -61,15 +70,16 @@ for opt in "${@}"; do
     fi
 done
 echo -e "\e[33mReading Databases...\e[0m"
+i=0
 while read line; do
     msg_tmp=(${line})
-    f[${i}]=${msg_tmp[1]}
-    m[${i}]=${msg_tmp[2]}
+    f[${i}]="${msg_tmp[1]}"
+    m[${i}]="${msg_tmp[2]}"
     uf[${i}]=false
     um[${i}]=false
     unset msg_tmp
     i=$(($i + 1))
-done <${LVCD}/MESSAGES
+done <"${LVCD}"/MESSAGES
 echo -e "\e[33mFiltering...\e[0m"
 if [ ${#sf[@]} -eq 0 ]; then
     for ((n = 0; n <= i; n++)); do
@@ -77,7 +87,7 @@ if [ ${#sf[@]} -eq 0 ]; then
     done
 else
     for item in "${sf[@]}"; do
-        for ((n = 0; n <= i; n++)); do
+        for ((n = 0; n <= i - 1; n++)); do
             if [[ ${f[${n}]} == *${item}* ]]; then
                 uf[${n}]=true
             fi
@@ -86,7 +96,7 @@ else
 fi
 if ! [ ${#se[@]} -eq 0 ]; then
     for item in "${se[@]}"; do
-        for ((n = 0; n <= i; n++)); do
+        for ((n = 0; n <= i - 1; n++)); do
             if [[ ${f[${n}]} == *${item}* ]]; then
                 uf[${n}]=false
             fi
@@ -99,7 +109,7 @@ if [ ${#sm[@]} -eq 0 ]; then
     done
 else
     for item in "${sm[@]}"; do
-        for ((n = 0; n <= i; n++)); do
+        for ((n = 0; n <= i - 1; n++)); do
             if [[ ${m[${n}]} == *${item}* ]]; then
                 um[${n}]=true
             fi
@@ -110,10 +120,10 @@ n=0
 while read line; do
     if ${uf[${n}]} && ${um[${n}]}; then
         msg_tmp=(${line})
-        echo -e "\e[31m[${msg_tmp[0]}]\e[0m \e[36m[${msg_tmp[1]}]\e[0m ${msg_tmp[2]}" >>${tmpfff}
+        echo -e "\e[31m[${msg_tmp[0]}]\e[0m \e[36m[${msg_tmp[1]}]\e[0m ${msg_tmp[2]}" >>"${tmpfff}"
     fi
     n=$((n + 1))
 done <${LVCD}/MESSAGES
-cat ${tmpfff} | sort | ${more}
+"${mycat}" "${tmpfff}" | "${mysort}" | "${more}"
 IFS=${OLD_IFS}
 exit 0
diff --git a/bin/pss b/bin/pss
--- a/bin/pss
+++ b/bin/pss
@@ -1,13 +1,13 @@
 #!/usr/bin/env bash
-# PSS V1P7
+# PSS V1P8
 echo -e "\e[33mYuZJLab Process Snapshot Searcher"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\e[0m"
+set -ue
 cd $(dirname ${0})
-{ . ../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || {
-    echo -e "\e[31mFail to load libisopt.\e[0m"
-    exit 1
-}
-more="more"
+. ../lib/libisopt
+. ../etc/path.sh
+more="${mymore}"
+STDS=''
 for opt in "${@}"; do
     if isopt ${opt}; then
         case ${opt} in
@@ -16,11 +16,17 @@ for opt in "${@}"; do
             exit 0
             ;;
         "-v" | "--version")
-            echo "Version 1 patch 7"
+            echo "Version 1 patch 8"
             exit 0
             ;;
         --more\:*)
-            more=${opt:7}
+            more="${opt:7}"
+            if ! "${more}" --help &>/dev/null; then
+                echo -e "\e[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\e[0m"
+                more="${mymore}"
+            else
+                echo -e "\e[33mWill use '${more}' as More.\e[0m"
+            fi
             ;;
         *)
             echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
@@ -33,21 +39,21 @@ for opt in "${@}"; do
 done
 psstmp=$(mktemp -t psstmp.XXXXXX)
 pssstmp=$(mktemp -t psstmp.XXXXXX)
-if [[ ${OSTYPE} = *BSD ]];then
-    /bin/ps -a -l >${psstmp}
-elif [[ $(ps --version) = *cygwin* ]];then
-    /usr/bin/ps -W >${psstmp}
+if [[ ${OSTYPE} == *BSD ]]; then
+    "${myps}" -a -l >"${psstmp}"
+elif [[ $("${myps}" --version) == *cygwin* ]]; then
+    "${myps}" -W >"${psstmp}"
 else
-    /bin/ps -A all >${psstmp}
+    "${myps}" -A all >"${psstmp}"
 fi
 if [ -z "${STDS}" ]; then
-    cat ${psstmp} | ${more}
+    "${mycat}" "${psstmp}" | "${more}"
 else
-    head -n 1 ${psstmp}
+    ${myhead} -n 1 ${psstmp}
     STDI=(${STDS})
     for fn in "${STDI[@]}"; do
-        cat ${psstmp} | grep -- ${fn} >>${pssstmp}
+        "${mycat}" "${psstmp}" | "${mygrep}" -- "${fn}" >>"${pssstmp}"
     done
-    cat ${pssstmp} | ${more}
+    "${mycat}" "${pssstmp}" | "${more}"
 fi
-rm ${psstmp} ${pssstmp}
+"${myrm}" "${psstmp}" "${pssstmp}"
diff --git a/bin/yldoc b/bin/yldoc
--- a/bin/yldoc
+++ b/bin/yldoc
@@ -1,30 +1,36 @@
 #!/usr/bin/env bash
-# YLDOC V1P5
+# YLDOC V1P6
+set -ue
 DN=$(dirname ${0})
-more="more"
 echo -e "\e[33mYuZJLab Documentation System"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\e[0m"
-{ . $DN/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || {
-    echo -e "\e[31mFail to load libisopt.\e[0m"
-    exit 1
-}
+. ${DN}/../lib/libisopt
+. "${DN}"/../etc/path.sh
+more="${mymore}"
+STDS=''
 for opt in "${@}"; do
-    if isopt ${opt}; then
-        case ${opt} in
+    if isopt "${opt}"; then
+        case "${opt}" in
         "-h" | "--help")
             yldoc yldoc
             exit 0
             ;;
         "-v" | "--version")
-            echo "Version 1 patch 5"
+            echo "Version 1 Patch 6"
             exit 0
             ;;
         --more\:*)
-            more=${opt:7}
+            more="${opt:7}"
+            if ! "${more}" --help &>/dev/null; then
+                echo -e "\e[31mERROR! Invalid More '${more}'! Will use original '${mymore}' instead.\e[0m"
+                more="${mymore}"
+            else
+                echo -e "\e[33mWill use '${more}' as More.\e[0m"
+            fi
             ;;
         "-l" | "--list")
             echo -e "\e[33mReading database...\e[0m"
-            ls -1 ${DN}/../doc | sort | sed 's/.usage//'|${more}
+            "${myls}" -1 "${DN}"/../doc | "${mysort}" | "${mysed}" 's/.usage//' | "${more}"
             exit 0
             ;;
         *)
@@ -36,12 +42,12 @@ for opt in "${@}"; do
         STDS="${STDS} ${opt}"
     fi
 done
-if [ -z ${STDS} ]; then
+if [ -z "${STDS}" ]; then
     yldoc yldoc
     exit 0
 fi
 STDI=(${STDS})
-if [ -f ${DN}/../etc/yldoc.conf ]; then
+if [ -f "${DN}"/../etc/yldoc.conf ]; then
     while read line; do
         li=(${line})
         for ((i = 0; i < ${#STDI[@]}; i++)); do
@@ -49,11 +55,11 @@ if [ -f ${DN}/../etc/yldoc.conf ]; then
                 STDI[${i}]=${li[1]}
             fi
         done
-    done <${DN}/../etc/yldoc.conf
+    done <"${DN}"/../etc/yldoc.conf
 fi
 for fn in "${STDI[@]}"; do
-    if [ -f ${DN}/../doc/${fn}.usage ]; then
-        cat ${DN}/../doc/${fn}.usage | ${more}
+    if [ -f "${DN}"/../doc/"${fn}".usage ]; then
+        "${mycat}" "${DN}"/../doc/"${fn}".usage | "${more}"
     else
         echo -e "\e[31mERROR: ${DN}/../doc/${fn}.usage not found!\e[0m"
         exit 1
