lcman support multiple arguments with new syntax.

diff --git a/bin/lcman b/bin/lcman
--- a/bin/lcman
+++ b/bin/lcman
@@ -1,66 +1,123 @@
 #!/bin/bash
-# LCMAN V2P1
-echo -e "\e[33mInitializing...\e[0m"
+# LCMAN V3
 DN=$(dirname ${0})
 LVCD="${DN}/../var/livechat.d"
 if [ ! -e ${LVCD}/MESSAGES ]; then
     echo -e "\e[31mERROR: livechat.d/MESSAGES not exist.\e[0m"
     exit 1
 fi
-OLD_IFS="$IFS"
+OLD_IFS="${IFS}"
 IFS=";"
-case $1 in
-"-s")
-    i=0
-    while read line; do
-        msg_tmp=(${line})
-        t[$i]=${msg_tmp[0]}
-        f[$i]=${msg_tmp[1]}
-        m[$i]=${msg_tmp[2]}
-        unset msg_tmp
-        i=$(($i + 1))
-    done <${LVCD}/MESSAGES
-    case $2 in
-    "from")
+tmpfff=$(mktemp -t lcman.XXXXXX)
+{ . $DN/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || {
+    echo -e "\e[31mFail to load libisopt.\e[0m"
+    exit 1
+}
+more="more"
+for opt in "${@}"; do
+    if isopt ${opt}; then
+        case ${opt} in
+        "-v")
+            echo -e "\e[33mVersion 3, compatiable with LiveChat Version 1 & 2.\e[0m"
+            exit 0
+            ;;
+        "-h")
+            yldoc lcman
+            exit 0
+            ;;
+        --more\:*)
+            more=${opt:7}
+            ;;
+        -f\:*)
+            sf=(${sf[@]} ${opt:3})
+            ;;
+        -m\:*)
+            sm=(${sm[@]} ${opt:3})
+            ;;
+        --from\:*)
+            sf=(${sf[@]} ${opt:7})
+            ;;
+        --message\:*)
+            sm=(${sm[@]} ${opt:10})
+            ;;
+        -e\:*)
+        se=(${se[@]} ${opt:3})
+        ;;
+            --exclude\:*)
+        se=(${se[@]} ${opt:10})
+        ;;
+        "-s"|"--exclude-system")
+        se=(${se[@]} "SYSTEM")
+        ;;
+        *)
+            echo -e "\e[31mERROR: Option '${opt}' invalid.\e[0m"
+            exit 1
+            ;;
+        esac
+    else
+        STDS="${STDS} ${opt}"
+    fi
+done
+echo -e "\e[33mReading Databases...\e[0m"
+while read line; do
+    msg_tmp=(${line})
+    f[${i}]=${msg_tmp[1]}
+    m[${i}]=${msg_tmp[2]}
+    uf[${i}]=False
+    um[${i}]=False
+    unset msg_tmp
+    i=$(($i + 1))
+done <${LVCD}/MESSAGES
+echo -e "\e[33mFiltering...\e[0m"
+if [ ${#sf[@]} -eq 0 ]; then
+    for ((n = 0; n <= i; n++)); do
+        uf[${n}]=True
+    done
+    else
+    for item in "${sf[@]}"; do
         for ((n = 0; n <= i; n++)); do
-            if [[ ${f[$n]} == *${3}* ]]; then
-                echo -e "\e[31m[${t[$n]}]\e[0m \e[36m[${f[$n]}]\e[0m ${m[$n]}"
+            if [[ ${f[${n}]} == *${item}* ]]; then
+                uf[${n}]=True
             fi
         done
-        ;;
-    "message")
+    done
+fi
+if [ ${#se[@]} -eq 0 ]; then
+    for ((n = 0; n <= i; n++)); do
+        uf[${n}]=True
+    done
+    else
+    for item in "${se[@]}"; do
         for ((n = 0; n <= i; n++)); do
-            if [[ ${m[$n]} == *"${3}"* ]]; then
-                echo -e "\e[31m[${t[$n]}]\e[0m \e[36m[${f[$n]}]\e[0m ${m[$n]}"
+            if [[ ${f[${n}]} == *${item}* ]]; then
+                uf[${n}]=False
             fi
         done
-        ;;
-    *)
-        echo -e "\e[31mERROR: Cannot understand \"-s ${2}\".\e[0m"
-        echo -e "\e[31mERROR: Available arguments: from, message.\e[0m"
-        exit 1
-        ;;
-    esac
-    unset i
-    ;;
-"-l")
-    while read line; do
+    done
+fi
+if [ ${#sm[@]} -eq 0 ]; then
+    for ((n = 0; n <= i; n++)); do
+        um[${n}]=True
+    done
+    else
+    for item in "${sm[@]}"; do
+        for ((n = 0; n <= i; n++)); do
+
+            if [[ ${m[${n}]} == *${item}* ]]; then
+                um[${n}]=True
+
+            fi
+        done
+    done
+fi
+n=0
+while read line; do
+    if ${uf[${n}]} && ${um[${n}]}; then
         msg_tmp=(${line})
-        echo -e "\e[31m[${msg_tmp[0]}]\e[0m \e[36m[${msg_tmp[1]}]\e[0m ${msg_tmp[2]}"
-    done <${LVCD}/MESSAGES
-    ;;
-"-v")
-    echo -e "\e[33mVersion 2 Patch 1, compatiable with LiveChat Version 1 & 2.\e[0m"
-    exit 0
-    ;;
-"-h")
-    yldoc lcman
-    exit 0
-    ;;
-*)
-    echo -e "\e[31mERROR: Cannot understand \"${1}\".\e[0m"
-    echo -e "\e[31mERROR: Available options: -s, -l, -h, -v.\e[0m"
-    ;;
-esac
+        echo -e "\e[31m[${msg_tmp[0]}]\e[0m \e[36m[${msg_tmp[1]}]\e[0m ${msg_tmp[2]}" >>${tmpfff}
+    fi
+    n=$((n + 1))
+done <${LVCD}/MESSAGES
+cat ${tmpfff} | sort | ${more}
 IFS=${OLD_IFS}
 exit 0
