[EMERGENCY] LiveChat ${DN} bug fixed

diff --git a/bin/livechat b/bin/livechat
--- a/bin/livechat
+++ b/bin/livechat
@@ -1,5 +1,5 @@
 #! /bin/bash
-# LIVECHAT V1P4
+# LIVECHAT V1EP5
 function sdmess(){
     echo "`date +%Y-%m-%d,%H:%M:%S`;${1};${MESS_SD}">>MESSAGES
 }
@@ -22,7 +22,8 @@ function F_REC(){
         fi
     done
 }
-LVCD="$DN/../var/livechat.d"
+DN=$(dirname ${0})
+LVCD="${DN}/../var/livechat.d"
 if [ -e ${LVCD} ];then
     if [ -f ${LVCD} ];then
         echo -e "\e[31mERROR: \"${LVCD}\" is a file rather than a directory.\e[0m"
@@ -40,7 +41,7 @@ cd ${LVCD}
 unset LVCD
 echo -e "\e[33mWelcome to YuZJLab LiveChat"
 echo -e "Copyright (C) 2019-2020 YU Zhejian\e[0m"
-{ . $DN/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || { echo -e "\e[31mFail to load libisopt.\e[0m";exit 1; }
+{ . ${DN}/../lib/libisopt; } && { echo -e "\e[33mlibisopt loaded\e[0m"; } || { echo -e "\e[31mFail to load libisopt.\e[0m";exit 1; }
 for opt in "${@}"; do
     if isopt ${opt}; then
         case ${opt} in
@@ -49,7 +50,7 @@ for opt in "${@}"; do
             exit 0
             ;;
         "-v" | "--version")
-            echo "Version 1 patch 4"
+            echo "Version 1 emergency patch 5"
             exit 0
             ;;
         *)
