indent changed to modified Google style.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,22 +1,22 @@
 #!/usr/bin/env bash
-VERSION=2.4
+VERSION=2.5
 set -eu
-if [ ${BASH_VERSINFO[0]} -lt 4 ] && [ ${BASH_VERSINFO[1]} -lt 4 ];then
-	echo -e "\033[31mERROR: Your Bash is obsolete.
+if [ ${BASH_VERSINFO[0]} -lt 4 ] && [ ${BASH_VERSINFO[1]} -lt 4 ]; then
+    echo -e "\033[31mERROR: Your Bash is obsolete.
 To run LinuxMiniPrograms, you need Bash >=4.4\033[0m"
 fi
 OLDIFS="${IFS}"
 if ! readlink -f . &>/dev/null; then
-	if ! greadlink -f . &>/dev/null; then
-		echo -e "\033[31mERROR: NO readlink & greadlink available
+    if ! greadlink -f . &>/dev/null; then
+        echo -e "\033[31mERROR: NO readlink & greadlink available
 For MacOS users, please install 'coreutils' by HomeBrew
 For BSD users, please install 'coreutils' by your package management systems\033[0m"
-		exit 1
-	else
-		ln -s "$(which greadlink)" "$(greadlink -f "$(dirname "${0}")")"/bin/readlink || true
-		PATH="$(greadlink -f "$(dirname "${0}")")/bin:${PATH}"
-		export PATH
-	fi
+        exit 1
+    else
+        ln -s "$(which greadlink)" "$(greadlink -f "$(dirname "${0}")")"/bin/readlink || true
+        PATH="$(greadlink -f "$(dirname "${0}")")/bin:${PATH}"
+        export PATH
+    fi
 fi
 cd "$(readlink -f "$(dirname "${0}")")"
 . lib/libisopt
@@ -38,65 +38,65 @@ PREFIX="${HOME}/usr/local"
 # ========Read Opt========
 STDS=()
 for opt in "${@}"; do
-	if isopt "${opt}"; then
-		case "${opt}" in
-		"-v" | "--version")
-			echo ${VERSION}
-			exit 0
-			;;
-		"-h" | "--help")
-			cat src/doc/configure.txt
-			exit 0
-			;;
-		"-a" | "--all")
-			VAR_install_config=true
-			VAR_clear_history=true
-			VAR_install_man=true
-			VAR_install_html=true
-			VAR_install_pdf=true
-			VAR_install_usage=true
-			;;
-		"--install-config")
-			VAR_install_config=true
-			;;
-		"--clear-history")
-			VAR_clear_history=true
-			;;
-		"--install-doc")
-			VAR_install_man=true
-			VAR_install_html=true
-			VAR_install_pdf=true
-			VAR_install_usage=true
-			;;
-		"--install-man")
-			VAR_install_man=true
-			;;
-		"--install-html")
-			VAR_install_html=true
-			;;
-		"--install-pdf")
-			VAR_install_pdf=true
-			;;
-		"--install-usage")
-			VAR_install_usage=true
-			;;
-		"--skip-path")
-			VAR_update_path=false
-			;;
-			# TODO: Implement installation
-			#--prefix\:*)
-			#	PREFIX="${opt:8}"
-			#	;;
-		"-x")
-			set -x
-			;;
-		*)
-			warnh "Option '${opt}' invalid. Ignored"
-			;;
-		esac
-	else
-		STDS=("${STDS[@]}" "${opt}")
-	fi
+    if isopt "${opt}"; then
+        case "${opt}" in
+        "-v" | "--version")
+            echo ${VERSION}
+            exit 0
+            ;;
+        "-h" | "--help")
+            cat src/doc/configure.txt
+            exit 0
+            ;;
+        "-a" | "--all")
+            VAR_install_config=true
+            VAR_clear_history=true
+            VAR_install_man=true
+            VAR_install_html=true
+            VAR_install_pdf=true
+            VAR_install_usage=true
+            ;;
+        "--install-config")
+            VAR_install_config=true
+            ;;
+        "--clear-history")
+            VAR_clear_history=true
+            ;;
+        "--install-doc")
+            VAR_install_man=true
+            VAR_install_html=true
+            VAR_install_pdf=true
+            VAR_install_usage=true
+            ;;
+        "--install-man")
+            VAR_install_man=true
+            ;;
+        "--install-html")
+            VAR_install_html=true
+            ;;
+        "--install-pdf")
+            VAR_install_pdf=true
+            ;;
+        "--install-usage")
+            VAR_install_usage=true
+            ;;
+        "--skip-path")
+            VAR_update_path=false
+            ;;
+            # TODO: Implement installation
+            #--prefix\:*)
+            #	PREFIX="${opt:8}"
+            #	;;
+        "-x")
+            set -x
+            ;;
+        *)
+            warnh "Option '${opt}' invalid. Ignored"
+            ;;
+        esac
+    else
+        STDS=("${STDS[@]}" "${opt}")
+    fi
 done
 
 # ========Check========
@@ -106,103 +106,103 @@ path_sh="etc/path.conf"
 ${VAR_update_path} && rm -f "${path_sh}"
 if [ ! -f "${path_sh}" ] && [ -f 'etc/path.sh' ]; then mv 'etc/path.sh' "${path_sh}"; fi
 if [ ! -f "${path_sh}" ]; then
-	mkdir -p etc
-	touch "${path_sh}"
-	echo "#!/usr/bin/env bash" >>"${path_sh}"
-	echo "# Generated at $(date)" >>"${path_sh}"
-	#=====os=====
-	if [ -z "${myos:-}" ]; then
-		mapfile < <(uname -mrs | tr ' ' '\n') # Do not use pipes; it will initiate a subshell
-		echo "myos=\"$(printf ${MAPFILE[1]})\" # $(printf ${MAPFILE[2]})" # >>"${path_sh}"
-	fi
-	#=====path=====
-	infoh "Enumerating valid path..."
-	# shellcheck disable=SC2034
-	INPATH="${PATH}"
-	. lib/libpath
-	unset invalid_path duplicated_path
-	IFS=':'
-	# shellcheck disable=SC2034
-	eachpath=(${valid_path})
-	IFS=''
-	unset binpath
-	echo ${valid_path} | tr ':' '\n'
-	infoh "End locating valid path"
-	unset valid_path
-	# shellcheck disable=SC1090
-	for PROGNAME in ps python; do . "src/exec/find${PROGNAME}.sh"; done
-	for PROGNAME in 7z 7za bgzip brotli bzip2 compress gzip lz4 lzfse lzip lzma lzop pbz2 pbzip pbzip2 pigz rar tar unzip unrar xz zip zstd \
-		asciidoc asciidoctor-pdf asciidoctor \
-		parallel \
-		git clang gcc make \
-		sed grep split \
-		gtar gsed ggrep gmake gsplit; do . src/exec/findornot.sh; done
-	# To change myasciidoctor-pdf because bash do not support variable names with '-' inside
-	sed -i".bak" 's;^myasciidoctor-pdf;myasciidoctor_pdf;' "${path_sh}"
-	. "${path_sh}"
-	[ "${mypbz2}" == 'ylukh' ] && [ "${mypbzip}" != 'ylukh' ] && sed -i".bak" 's;^mypbzip;mypbz2;' "${path_sh}"
-	. "${path_sh}"
-	[ "${mypbz2}" == 'ylukh' ] && [ "${mypbzip2}" != 'ylukh' ] && sed -i".bak" 's;^mypbzip2;mypbz2;' "${path_sh}"
-	. "${path_sh}"
-	# Remove g for GNU CoreUtils installed under BSD systems
-	[ "${mygtar}" != 'ylukh' ] && sed -i".bak" 's;^mygtar;mytar;' "${path_sh}"
-	[ "${mygsed}" != 'ylukh' ] && sed -i".bak" 's;^mygsed;mysed;' "${path_sh}"
-	[ "${myggrep}" != 'ylukh' ] && sed -i".bak" 's;^myggrep;mygrep;' "${path_sh}"
-	[ "${mygmake}" != 'ylukh' ] && sed -i".bak" 's;^mygmake;mymake;' "${path_sh}"
-	[ "${mygsplit}" != 'ylukh' ] && sed -i".bak" 's;^mygsplit;mysplit;' "${path_sh}"
-	infoh "All configurations are printed as follows:"
-	cat "${path_sh}" | grep -v '^$' | grep -v '^#' | sed 's/^my//' | sed 's/=/\\\\033[33m in \\\\033[0m/ ' | sed 's/ #/\\\\033[33m, \\\\033[32m/' | sort | while read line; do echo -e "${line}\033[0m"; done
+    mkdir -p etc
+    touch "${path_sh}"
+    echo "#!/usr/bin/env bash" >>"${path_sh}"
+    echo "# Generated at $(date)" >>"${path_sh}"
+    #=====os=====
+    if [ -z "${myos:-}" ]; then
+        mapfile < <(uname -mrs | tr ' ' '\n')                             # Do not use pipes; it will initiate a subshell
+        echo "myos=\"$(printf ${MAPFILE[1]})\" # $(printf ${MAPFILE[2]})" # >>"${path_sh}"
+    fi
+    #=====path=====
+    infoh "Enumerating valid path..."
+    # shellcheck disable=SC2034
+    INPATH="${PATH}"
+    . lib/libpath
+    unset invalid_path duplicated_path
+    IFS=':'
+    # shellcheck disable=SC2034
+    eachpath=(${valid_path})
+    IFS=''
+    unset binpath
+    echo ${valid_path} | tr ':' '\n'
+    infoh "End locating valid path"
+    unset valid_path
+    # shellcheck disable=SC1090
+    for PROGNAME in ps python; do . "src/exec/find${PROGNAME}.sh"; done
+    for PROGNAME in 7z 7za bgzip brotli bzip2 compress gzip lz4 lzfse lzip lzma lzop pbz2 pbzip pbzip2 pigz rar tar unzip unrar xz zip zstd \
+        asciidoc asciidoctor-pdf asciidoctor \
+        parallel \
+        git clang gcc make \
+        sed grep split \
+        gtar gsed ggrep gmake gsplit; do . src/exec/findornot.sh; done
+    # To change myasciidoctor-pdf because bash do not support variable names with '-' inside
+    sed -i".bak" 's;^myasciidoctor-pdf;myasciidoctor_pdf;' "${path_sh}"
+    . "${path_sh}"
+    [ "${mypbz2}" == 'ylukh' ] && [ "${mypbzip}" != 'ylukh' ] && sed -i".bak" 's;^mypbzip;mypbz2;' "${path_sh}"
+    . "${path_sh}"
+    [ "${mypbz2}" == 'ylukh' ] && [ "${mypbzip2}" != 'ylukh' ] && sed -i".bak" 's;^mypbzip2;mypbz2;' "${path_sh}"
+    . "${path_sh}"
+    # Remove g for GNU CoreUtils installed under BSD systems
+    [ "${mygtar}" != 'ylukh' ] && sed -i".bak" 's;^mygtar;mytar;' "${path_sh}"
+    [ "${mygsed}" != 'ylukh' ] && sed -i".bak" 's;^mygsed;mysed;' "${path_sh}"
+    [ "${myggrep}" != 'ylukh' ] && sed -i".bak" 's;^myggrep;mygrep;' "${path_sh}"
+    [ "${mygmake}" != 'ylukh' ] && sed -i".bak" 's;^mygmake;mymake;' "${path_sh}"
+    [ "${mygsplit}" != 'ylukh' ] && sed -i".bak" 's;^mygsplit;mysplit;' "${path_sh}"
+    infoh "All configurations are printed as follows:"
+    cat "${path_sh}" | grep -v '^$' | grep -v '^#' | sed 's/^my//' | sed 's/=/\\\\033[33m in \\\\033[0m/ ' | sed 's/ #/\\\\033[33m, \\\\033[32m/' | sort | while read line; do echo -e "${line}\033[0m"; done
 fi
 for STDI in "${STDS[@]}"; do
-	echo my"${STDI}" >>"${path_sh}"
+    echo my"${STDI}" >>"${path_sh}"
 done
 . etc/path.conf
 [ "${mymake}" = "ylukh" ] && errh "GNU Make not found"
 #========Install ETC========
 if ${VAR_install_config} && [ -d "etc" ]; then
-	"${mytar}" czf etc_backup.tgz etc
-	infoh "Backing up settings...\033[32mPASSED"
+    "${mytar}" czf etc_backup.tgz etc
+    infoh "Backing up settings...\033[32mPASSED"
 fi
 #========Install VAR========
 if ${VAR_clear_history} && [ -d "var" ]; then
-	"${mytar}" czf var_backup.tgz var
-	infoh "Backing up histories...\033[32mPASSED"
+    "${mytar}" czf var_backup.tgz var
+    infoh "Backing up histories...\033[32mPASSED"
 fi
 #========Install DOC========
 if [ "${myasciidoctor}" == "ylukh" ]; then
-	VAR_install_man=false
-	[ "${myasciidoc}" == "ylukh" ] && VAR_install_html=false
+    VAR_install_man=false
+    [ "${myasciidoc}" == "ylukh" ] && VAR_install_html=false
 fi
 [ "${myasciidoctor_pdf}" != "ylukh" ] || VAR_install_pdf=false
 [ "${mypython}" != "ylukh" ] || VAR_install_usage=false
 if ${VAR_install_pdf}; then
-	MAKE_TARGETS="${MAKE_TARGETS} share/doc/pdf"
-	MAKE_ARGS="${MAKE_ARGS}:ADOC_PDF=\"${myasciidoctor_pdf}\""
+    MAKE_TARGETS="${MAKE_TARGETS} share/doc/pdf"
+    MAKE_ARGS="${MAKE_ARGS}:ADOC_PDF=\"${myasciidoctor_pdf}\""
 fi
 if ${VAR_install_man}; then
-	MAKE_TARGETS="${MAKE_TARGETS} share/man"
-	MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
+    MAKE_TARGETS="${MAKE_TARGETS} share/man"
+    MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
 fi
 if ${VAR_install_usage}; then
-	MAKE_TARGETS="${MAKE_TARGETS} share/doc/usage"
-	MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
+    MAKE_TARGETS="${MAKE_TARGETS} share/doc/usage"
+    MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
 fi
 if ${VAR_install_html}; then
-	if [ "${myasciidoctor}" != "ylukh" ]; then
-		MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
-	else
-		MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoc}\":AOPT=\"\""
-	fi
-	MAKE_TARGETS="${MAKE_TARGETS} share/doc/html"
+    if [ "${myasciidoctor}" != "ylukh" ]; then
+        MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoctor}\""
+    else
+        MAKE_ARGS="${MAKE_ARGS}:ADOC=\"${myasciidoc}\":AOPT=\"\""
+    fi
+    MAKE_TARGETS="${MAKE_TARGETS} share/doc/html"
 fi
 #========C========
 [ "${mygcc}" != "ylukh" ] || [ "${myclang}" != "ylukh" ] && MAKE_TARGETS="${MAKE_TARGETS} C"
 if cat "${path_sh}" | grep -i BSD >/dev/null; then
-	MAKE_ARGS="${MAKE_ARGS}:CC=${myclang}" # Use Clang for FreeBSD.
+    MAKE_ARGS="${MAKE_ARGS}:CC=${myclang}" # Use Clang for FreeBSD.
 elif [ "${mygcc}" != "ylukh" ]; then
-	MAKE_ARGS="${MAKE_ARGS}:CC=${mygcc}"
+    MAKE_ARGS="${MAKE_ARGS}:CC=${mygcc}"
 elif [ "${myclang}" != "ylukh" ]; then
-	MAKE_ARGS="${MAKE_ARGS}:CC=${myclang}"
+    MAKE_ARGS="${MAKE_ARGS}:CC=${myclang}"
 fi
 #========Makefile Generation========
 MAKE_ARGS="${MAKE_ARGS}:PYTHON=${mypython}:RM=rm -rf:CP=cp -rf:PREFIX=${PREFIX}"
diff --git a/lib/libstr b/lib/libstr
--- a/lib/libstr
+++ b/lib/libstr
@@ -1,20 +1,20 @@
 #!/usr/bin/env bash
-# VERSION=1.2
+# VERSION=1.3
 trimstr() {
-	: "${1#"${1%%[![:space:]]*}"}" # Trim trailing space
-	: "${_%"${_##*[![:space:]]}"}" # Trim leading space
-	printf '%s\n' "${_}"
+    : "${1#"${1%%[![:space:]]*}"}" # Trim trailing space
+    : "${_%"${_##*[![:space:]]}"}" # Trim leading space
+    printf '%s\n' "${_}"
 }
 
 errh() {
-	echo -e "\033[31mERROR: ${*}\033[0m" >&2
-	exit 1
+    echo -e "\033[31mERROR: ${*}\033[0m" >&2
+    exit 1
 }
 
 warnh() {
-	echo -e "\033[31mWARNING: ${*}\033[0m" >&2
+    echo -e "\033[31mWARNING: ${*}\033[0m" >&2
 }
 
 infoh() {
-	echo -e "\033[33mINFO: ${*}\033[0m" >&2
+    echo -e "\033[33mINFO: ${*}\033[0m" >&2
 }
