Release 1

diff --git a/LibDOManager/libdoman b/LibDOManager/libdoman
--- a/LibDOManager/libdoman
+++ b/LibDOManager/libdoman
@@ -9,23 +9,25 @@ else
     echo -e "\e[31mERROR: libisopt not found.\e[0m">&2
     exit 1
 fi
+more="more"
 for opt in $@;do
     if isopt $opt;then
         case $opt in
             "-h"|"--help")
-                echo -e "\e[31mThis is a LibDO Log Manager. Useage:"
+                echo -e "\e[33mThis is a LibDO Log Manager. Useage:"
                 echo "libdo_man [libdo_output] [options]"
                 echo
                 echo "Available options:"
                 echo "  -h|--help Dicplay this help."
                 echo "  -v|--version Print version information."
                 echo "  -s|--summary Print summary."
-                echo "  -o:[item]|--output:[item] Get the output of [item]."
+                echo "  -o:[item]|--output:[item] Get the output of [item] (from 1)."
+                echo "  --more:[program]|The GNU/Linux program \"more\" will be used if there's too much output. Use [program] to replace it."
                 echo -e "\e[0m"
                 exit 0
             ;;
             "-v"|"--version")
-                echo -e "\e[31mVersion 1, compatiable with libdo Version 1.\e[0m"
+                echo -e "\e[31mVersion 1 released, compatiable with libdo Version 1.\e[0m"
                 exit 0
             ;;
             "-s"|"--summary")
@@ -36,6 +38,9 @@ for opt in $@;do
             ;;
             --output\:*)
                 cmd=${opt:9}
+            ;;
+            --more\:*)
+                more=${opt:7}
             ;;
             *)
                 echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
@@ -54,47 +59,51 @@ if ! [ -f $fn ];then
 fi
 echo -e "\e[33mReceived: $0 $fn $OPT \e[0m"
 summary=`mktemp -t libdo_man.XXXXXX`
-cat $fn|grep LIBDO>$summary
-Proj=1
+cat $fn> $summary
+echo -e "\e[33mTemporay file created. \e[0m"
+Proj=0
 ln=0
-status=4
+status=2
 while read line;do
     ln=$[$ln+1]
     case $line in
         "LIBDO IS GOING TO EXECUTE"*)
-            if [ $status -ge 1 ] && [ $status -le 2 ];then
-                Proj=$[$Proj+1]
+            if [ $status -eq 1 ];then
                 Proj_Cont_e[$Proj]=$[$ln-1]
                 Proj_Time_e[$Proj]=0
-                Proj_Exit[$Proj]="-1"
+                Proj_Exit[$Proj]="-1."
             fi
+            Proj=$[$Proj+1]
             status=1
             Proj_CMD[$Proj]=${line:26}
         ;;
         "LIBDO STARTED AT"*)
-            Proj_Time_s[$Proj]=$ln
+            Proj_Time_s[$Proj]=${line:17}
         ;;
         "LIBDO PID"*)
-            status=2
             Proj_Cont_s[$Proj]=$[$ln+1]
         ;;
         "LIBDO STOPPED AT"*)
-            status=3
-            Proj_Time_e[$Proj]=$ln
+            Proj_Cont_e[$Proj]=$[$ln-1]
+            Proj_Time_e[$Proj]=${line:17}
         ;;
         "LIBDO EXITED SUCCESSFULLY.")
-            status=4
-            Proj_Exit[$Proj]="0"
+            status=2
+            Proj_Exit[$Proj]="0."
         ;;
         "LIBDO FAILED, GOT"*)
-            status=5
-            Proj_Exit[$Proj]=${line:19}
-        ;;
+            status=2
+            Proj_Exit[$Proj]=${line:21}
     esac
 done < $summary
-
-
+if [ $status -eq 1 ];then
+    Proj_Cont_e[$Proj]=$[$ln-1]
+    Proj_Time_e[$Proj]=0
+    Proj_Exit[$Proj]="-1"
+fi
+echo -e "\e[33mFile loaded \e[0m"
 if [ "$cmd" = 0 ];then
+    table=`mktemp -t libdo_man.XXXXXX`
     if [ -f $DN/../lib/libmktbl ] && [ -x $DN/../lib/libmktbl ];then
         . $DN/../lib/libmktbl
         echo -e "\e[33mlibmktbl loaded.\e[0m">&2
@@ -102,14 +111,26 @@ if [ "$cmd" = 0 ];then
         echo -e "\e[31mERROR: libmktbl not found.\e[0m">&2
         exit 1
     fi
-    echo -e "\#\n\#1S10\n\#1">table
+    echo -e "\#1\n\#S100\n\#1">$table
+    echo "Index;COMMAND;EXIT_STATUS">>$table
     for ((i=1;i<=$Proj;i++));do
-        echo "$i;${Proj_CMD[$i]};${Proj_Exit[$i]}"|sed "s/ /_/g">>table
+        echo "$i;${Proj_CMD[$i]};${Proj_Exit[$i]}"|sed "s/ /_/g">>$table
     done
-    mktbl table
+    mktbl $table
+    rm $table
 else
-echo "s"
+    if [ $Proj -lt $cmd ];then echo -e "\e[31mERROR: $cmd too large.\e[0m">&2;exit 1;fi
+    echo "JOB_CMD     : ${Proj_CMD[$cmd]}"
+    echo "TIME        : ${Proj_Time_s[$cmd]} to ${Proj_Time_e[$cmd]}"
+    echo "EXIT_STATUS : ${Proj_Exit[$cmd]}"
+    echo "__________JOB_OUTPUT__________"
+    if [ ${Proj_Cont_s[$cmd]} -ge ${Proj_Cont_e[$cmd]} ];then
+        echo -e "\e[33mNO_OUTPUT\e[0m"
+    else
+        cat -n  $summary|head -n $[${Proj_Cont_e[$cmd]}]|tail -n $[${Proj_Cont_e[$cmd]}-${Proj_Cont_s[$cmd]}+1]|$more
+    fi
+    echo "_____JOB_OUTPUT_FINISHED______"
 fi
-
-
 rm $summary
+echo -e "\e[33mFinished.\e[0m">&2
+exit 0
