Changes in CTest and tetgs synced

diff --git a/lib/libstr b/lib/libstr
--- a/lib/libstr
+++ b/lib/libstr
@@ -1,20 +1,48 @@
 #!/usr/bin/env bash
-# VERSION=1.3
+# VERSION=1.4
+
+# Check for color support
+RED=""
+GREEN=""
+YELLOW=""
+BLUE=""
+PURPLE=""
+CRAYON=""
+NOCOLOR=""
+HAVE_COLOR=0
+COLORS="$(tput colors 2> /dev/null)" || true
+# shellcheck disable=SC2086
+[ ${COLORS} -gt 2 ] && HAVE_COLOR=1
+[[ "${TERM:-}" =~ "256" ]] && HAVE_COLOR=1
+if [ ${HAVE_COLOR} -eq 1 ];then
+    RED="\033[31m"
+    # shellcheck disable=SC2034
+    GREEN="\033[32m"
+    YELLOW="\033[33m"
+    # shellcheck disable=SC2034
+    BLUE="\033[34m"
+    # shellcheck disable=SC2034
+    PURPLE="\033[35m"
+    # shellcheck disable=SC2034
+    CRAYON="\033[36m"
+    NOCOLOR="\033[0m"
+fi
+
 trimstr() {
-    : "${1#"${1%%[![:space:]]*}"}" # Trim trailing space
-    : "${_%"${_##*[![:space:]]}"}" # Trim leading space
-    printf '%s\n' "${_}"
+	: "${1#"${1%%[![:space:]]*}"}" # Trim trailing space
+	: "${_%"${_##*[![:space:]]}"}" # Trim leading space
+	printf '%s\n' "${_}"
 }
 
 errh() {
-    echo -e "\033[31mERROR: ${*}\033[0m" >&2
-    exit 1
+	builtin echo -e "${RED}ERROR: ${*}${NOCOLOR}" >&2
+	exit 1
 }
 
 warnh() {
-    echo -e "\033[31mWARNING: ${*}\033[0m" >&2
+	builtin echo -e "${RED}WARNING: ${*}${NOCOLOR}" >&2
 }
 
 infoh() {
-    echo -e "\033[33mINFO: ${*}\033[0m" >&2
+	builtin echo -e "${YELLOW}INFO: ${*}${NOCOLOR}" >&2
 }
