[EMERGENCY] tgz bugs fixed.

diff --git a/AutoZip/libautozip b/AutoZip/libautozip
--- a/AutoZip/libautozip
+++ b/AutoZip/libautozip
@@ -1,6 +1,25 @@
 #!/bin/bash
 USESPLIT=false
 REMOVE=false
+#Load libopt
+if [ -f $DN/../lib/libisopt ] && [ -x $DN/../lib/libisopt ];then
+    . $DN/../lib/libisopt
+    echo -e "\e[33mlibisopt loaded.\e[0m">&2
+else
+    echo -e "\e[31mERROR: libisopt not found.\e[0m">&2
+    exit 1
+fi
+#Load libdo
+if [ -f $DN/../lib/libdo ] && [ -x $DN/../lib/libdo ];then
+    LIBDO_LOG=""
+    LIBDO_TOP_PID=$TOP_PID
+    LIBDO_PRD=true
+    . $DN/../lib/libdo
+    echo -e "\e[33mlibdo loaded.\e[0m">&2
+else
+    echo -e "\e[31mERROR: libdo not found.\e[0m">&2
+    exit 1
+fi
 # Check for all compoments: backend.
 function preck(){
     TAR=`tar --help&>>/dev/null;echo $?`
@@ -116,22 +135,82 @@ function autozipck(){
     cat $CONFN
     echo -e "\e[33m=====End   $CONFN=====\e[0m"
 }
-#Load libopt
-if [ -f $DN/../lib/libisopt ] && [ -x $DN/../lib/libisopt ];then
-    . $DN/../lib/libisopt
-    echo -e "\e[33mlibisopt loaded.\e[0m">&2
-else
-    echo -e "\e[31mERROR: libisopt not found.\e[0m">&2
-    exit 1
-fi
-#Load libdo
-if [ -f $DN/../lib/libdo ] && [ -x $DN/../lib/libdo ];then
-    LIBDO_LOG=""
-    LIBDO_TOP_PID=$TOP_PID
-    LIBDO_PRD=true
-    . $DN/../lib/libdo
-    echo -e "\e[33mlibdo loaded.\e[0m">&2
-else
-    echo -e "\e[31mERROR: libdo not found.\e[0m">&2
-    exit 1
-fi
+#Modify Filenames
+function mfn(){
+    echo $*|sed -e "s,(,\\\\\(,g"|sed -e "s,),\\\\\),g"|sed -e "s,\[,\\\\\[,g"|sed -e "s,\],\\\\\],g"|sed -e "s,<,\\\\\<,g"|sed -e "s,>,\\\\\>,g"|sed -e "s,{,\\\\\{,g"|sed -e "s,},\\\\\},g"
+}
+#Makt temporaty resources
+function mktmp(){
+    tempdir=`mktemp -dt autozip.XXXXXX`
+    tempf=`mktemp -t autozip.XXXXXX`
+    echo -e "\e[33mTEMP file '$tempf' and directory '$tempdir' made.\e[0m"
+}
+# Check opt
+function ppopt(){
+    for opt in $@;do
+        case $opt in
+            "-s"|"--split")
+                USESPLIT=true
+                case $ext in
+                    "rar"|"zip"|"7z")
+                        SPLIT=1024m
+                    ;;
+                    *)
+                        SPLIT=1G
+                esac
+            ;;
+            -s\:*)
+                USESPLIT=true
+                SPLIT=${opt:3}
+            ;;
+            --split\:*)
+                USESPLIT=true
+                SPLIT=${opt:8}
+            ;;
+        esac
+    done
+    for opt in $@;do
+        if isopt $opt;then
+            case $opt in
+                "-h"|"--help")
+                    if [ -f $DN/autozip.Usage ];then
+                        cat $DN/autozip.Usage
+                        exit 0
+                    else
+                        echo -e "\e[31mERROR: $DN/autozip.Usage not found!\e[0m"
+                        exit 1
+                    fi
+                ;;
+                "-v"|"--version")
+                    echo "Version 1 patch 2"
+                ;;
+                --force-parallel\:*)
+                    PP=${opt:17}
+                    if [ `$PP -h&>>/dev/null;echo $?` -eq 0 ];then
+                        USEPARALLEL=true
+                        echo -e "\e[33mWill use GNU Parallel in '$PP'.\e[0m"
+                    else
+                        echo -e "\e[31mERROR: GNU Parallel path '$PP' invalid.\e[0m"
+                        if [ $PARALLEL -eq 0 ];then PP="/usr/bin/parallel";echo -e "\e[31mERROR: Will use GNU Parallel in /usr/bin/parallel\e[0m";fi
+                    fi
+                ;;
+                "--remove")
+                    echo -e "\e[33mWARNING: Will remove $fn if success.\e[0m"
+                    REMOVE=true
+                ;;
+                "-s"|"--split"|-s\:*|--split\:*)
+                    if ! ISAUTOZIP; then
+                        echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
+                        exit 1
+                    fi
+                ;;
+                *)
+                    echo -e "\e[31mERROR: Option '$opt' invalid.\e[0m"
+                    exit 1
+            esac
+            OPT="$OPT $opt"
+        else
+            STDS="$STDS $opt"
+        fi
+    done
+}
